const phuongxaDakLak = [
   {
      id: 1,
      province: 26,
      image: ["hoa-phu-1.jpg", "hoa-phu-2.jpg"],
      name: "Xã Hoà Phú",
      introduce: `Xã Hòa Phú được hình thành từ quá trình sáp nhập các xã Hòa Phú, Hòa Xuân và Hòa Khánh `,
      square: `Diện tích khoảng 150 km²`,
      population: `Dân số hơn 25.000 người, bao gồm 13 thôn và 2 buôn.`,
      ethnic: `Xã Hòa Phú là nơi sinh sống của 12 dân tộc anh em, bao gồm người Kinh, Êđê, và các dân tộc thiểu số khác, tạo nên một bức tranh văn hóa phong phú và đa dạng.`,
      location: [
         `Phía Bắc: giáp ranh xã Ea Nuôl  `,
         `Phía Nam: giáp với xã Ea Na`,
         `Phía Đông: giáp với phường Thành Nhất, phường Ea Kao`,
         `Phía Tây: giáp với tỉnh Lâm Đồng `,
      ],
      economy: `Với địa hình cao nguyên đặc trưng và khí hậu ôn hòa, xã Hòa Phú không chỉ phù hợp cho phát triển nông nghiệp mà còn có tiềm năng lớn trong lĩnh vực du lịch sinh thái và dịch vụ. Sau sáp nhập, xã đã tận dụng tối đa các lợi thế này để thúc đẩy kinh tế và nâng cao chất lượng cuộc sống cho cư dân.`,
      info: [
         `Xã Hòa Phú tổ chức thường xuyên các lễ hội truyền thống như Lễ hội Cồng chiêng và các hoạt động văn hóa dân gian, thu hút sự tham gia của cả người dân địa phương và du khách.`,
         `Ẩm thực đặc trưng của xã Hòa Phú: Ẩm thực tại xã Hòa Phú là sự kết hợp giữa các món ăn truyền thống Tây Nguyên như cơm lam, gà nướng`,
      ],
   },
   {
      id: 2,
      province: 26,
      name: "Xã Ea Drông",
      image: ["ea-drong-1.jpg"],
      introduce: `Xã Ea Drông mới bao gồm toàn bộ diện tích của xã Ea Drông cũ (58,66 km²) và xã Ea Siên (52,47 km²). `,
      square: `Diện tích khoảng 111,13 km²`,
      population: `Dân số của xã đạt khoảng 23.522 người`,
      ethnic: `Xã Hòa Phú là nơi sinh sống của 12 dân tộc anh em, bao gồm người Kinh, Êđê, và các dân tộc thiểu số khác, tạo nên một bức tranh văn hóa phong phú và đa dạng.`,
      location: [
         `Phía đông: giáp xã Phú Xuân`,
         `Phía tây : giáp phường Buôn Hồ`,
         `Phía bắc: giáp xã Krông Năng`,
         `Phía Nam: phường Cư Pao, xã Ea Phê, xã Ea Kly`,
      ],
      economy: [
         `Với vị trí gần các khu vực sản xuất nông nghiệp và công nghiệp của thị xã Buôn Hồ, Xã Ea Drông có lợi thế trong việc thu hút đầu tư vào các ngành chế biến nông sản và dịch vụ. Các dự án giao thông liên tỉnh cũng giúp xã kết nối với các khu vực kinh tế trọng điểm như Khu công nghiệp Hòa Phú và sân bay Buôn Ma Thuột, cách xã khoảng 40 km.`,
         `Ea Drông nằm trên vùng đất bazan màu mỡ, phù hợp cho việc trồng cà phê, hồ tiêu, cao su và các cây công nghiệp khác.`,
      ],
      info: [
         `Đặc điểm văn hóa và xã hội: Sự đa dạng dân tộc tại Xã Ea Drông mang lại những giá trị văn hóa phong phú, với các lễ hội truyền thống như Lễ hội Cồng chiêng và các buôn làng đặc trưng của người Ê Đê. Xã cũng ghi nhận sự phát triển của các hợp tác xã như Ea Muich, Ea Ngăch, Ea Bar, đóng vai trò quan trọng trong việc thúc đẩy kinh tế cộng đồng và bảo tồn văn hóa bản địa.`,
         `Xã Ea Drông sở hữu các giá trị văn hóa bản địa đặc sắc, đặc biệt là văn hóa Ê Đê với các lễ hội truyền thống và không gian văn hóa cồng chiêng. Các buôn làng như Ea Muich, Ea Ngăch là điểm đến tiềm năng cho du lịch cộng đồng. `,
      ],
   },
   {
      id: 3,
      province: 26,
      name: "Xã Ea Súp",
      image: ["ea-sup-1.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của thị trấn Ea Súp, xã Cư M’Lan và xã Ea Lê thành xã mới có tên gọi là xã Ea Súp.`,
      square: `Diện tích khoảng 150 km² `,
      population: `Dân số của xã đạt khoảng 10.000 người`,
      ethnic: `Xã Ea Súp có sự kết hợp giữa người Kinh và các dân tộc thiểu số như Ê Đê, Tày, Nùng, chiếm khoảng 40% tổng dân số.`,
      location: [
         `Phía đông: giáp các xã Ea Khai, xã Ea Kiết, xã Buôn Đôn`,
         `Phía tây: giáp các xã Buôn Đôn, xã Ea Bung`,
         `Phía nam: giáp các xã Ea Rốk, Ia Lốp.`,
         `Phía bắc: giáp các xã Ea Rốk, xã Ea Wy `,
      ],
      economy: `Với vị trí gần hồ Ea Súp Thượng và Ea Súp Hạ, Xã Ea Súp có tiềm năng phát triển nông nghiệp và du lịch sinh thái. Các dự án giao thông liên huyện, như tuyến đường nối xã Ea Súp với xã Ia Lốp, giúp xã kết nối dễ dàng hơn với các khu vực kinh tế trọng điểm như Khu công nghiệp Hòa Phú và các trung tâm thương mại tại thành phố Buôn Ma Thuột.`,
      info: `Xã Ea Súp là một khu vực đa dạng về văn hóa, với các lễ hội truyền thống như Lễ hội Cồng chiêng của người Ê Đê và các hoạt động cộng đồng tại các thôn, buôn. Các hợp tác xã nông nghiệp và các tổ chức cộng đồng như Hội Nông dân, Hội Phụ nữ tại xã cũng đóng vai trò quan trọng trong việc thúc đẩy kinh tế và bảo tồn văn hóa bản địa`,
   },
   {
      id: 4,
      province: 26,
      name: "Xã Ea Rốk",
      image: ["ea-rok-1.jpg"],
      introduce: `Toàn bộ diện tích tự nhiên, quy mô dân số của các xã Ia Jlơi, Cư Kbang và Ea Rốk thành xã mới có tên gọi là xã Ea Rốk. `,
      square: `Diện tích tự nhiên khoảng 35.000 ha.`,
      population: `Dân số ban đầu khoảng 4.000 người,`,
      ethnic: `Xã Ea Rốk, huyện Ea Kar, tỉnh Đắk Lắk, có thành phần dân tộc đa dạng, trong đó chủ yếu là người Ê Đê và M'Nông. Ngoài ra, còn có các dân tộc khác như Tày, Nùng, Mường, Dao, Thái, Sán chỉ, Vân Kiều, Xơ Đăng, v.v., đến từ các địa phương khác. `,
      location: [
         `Phía Đông: giáp xã Ea H’leo, xã Ea Wy`,
         `Phía Tây: giáp xã Ia Lốp, xã Ia Rvê, xã Ea Bung`,
         `Phía Nam: giáp xã Ea Sup`,
         `Phía Bắc: giáp với tỉnh Gia Lai `,
      ],
      economy: `Xã Ea Rốk có nền kinh tế chủ yếu dựa vào nông nghiệp, đặc biệt là cây cao su và các loại cây trồng khác như cà phê, hồ tiêu. Ngoài ra, xã còn phát triển chăn nuôi và có tiềm năng trong thương mại biên giới với Campuchia`,
      info: [
         `Vị trí gần Tháp Chàm Yang Prong, một di tích văn hóa Chăm Pa nổi tiếng, giúp xã Ea Rốk có tiềm năng phát triển du lịch văn hóa và sinh thái. Các hoạt động thương mại biên giới cũng đang được khuyến khích để thúc đẩy giao lưu kinh tế với Campuchia.`,
         `Sự đa dạng về văn hóa đã tạo nên bản sắc độc đáo cho xã, với các lễ hội truyền thống và phong tục đặc sắc.`,
         `Người Ê Đê tại xã Ea Rốk vẫn duy trì các phong tục như lễ cúng bến nước, lễ mừng lúa mới và các điệu múa cồng chiêng truyền thống. `,
      ],
   },
   {
      id: 5,
      province: 26,
      name: "Xã Ea Bung",
      image: ["ea-bung-1.jpg", "ea-bung-2.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên từ xã Ya Tờ Mốt và xã Ea Bung thành xã mới có tên gọi là xã Ea Bung`,
      square: `Diện tích khoảng 466,08 km² `,
      population: `Dân số của xã đạt khoảng 8.189 người`,
      ethnic: `Đặc điểm nổi bật của xã là sự đa dạng về dân tộc, với nhiều dân tộc thiểu số cùng sinh sống, trong đó có người Ê Đê, M'Nông, Gia Rai và một số dân tộc khác.`,
      location: [
         `Phía Đông: giáp xã Ea Rốk, xã Ea Súp`,
         `Phía Tây: giáp Vương quốc Campuchia.`,
         `Phía Nam: giáp xã Ea Súp, xã Buôn Đôn`,
         `Phía Bắc: giáp xã Ia Rvê`,
      ],
      economy: `Tọa lạc ở khu vực biên giới phía Tây tỉnh Đắk Lắk, xã Ea Rốk có nền kinh tế chủ yếu dựa vào nông - lâm nghiệp. Cây cao su là loại cây trồng chiếm ưu thế, phát triển tốt trên nền đất bazan màu mỡ, mang lại thu nhập ổn định cho hàng trăm hộ dân.`,
      info: [
         `Xã Ea Bung là nơi sinh sống của nhiều dân tộc thiểu số, đặc biệt là người Ê Đê và M'Nông, với những phong tục, tập quán, lễ hội truyền thống riêng.`,
         `Các lễ hội như mừng lúa mới, cúng bến nước, và các hoạt động văn hóa như múa cồng chiêng, nhà dài vẫn được duy trì và phát triển`,
         `Các di tích lịch sử, văn hóa như Tháp Chàm Yang Prong`,
      ],
   },
   {
      id: 6,
      province: 26,
      name: "Xã Ea Wer",
      image: ["ea-wer-1.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của các xã Ea Huar, Tân Hòa và Ea Wer thành xã mới có tên gọi là xã Ea Wer.`,
      square: `Diện tích tự nhiên khoảng 6.000 ha, chủ yếu là đất nông nghiệp và lâm nghiệp.`,
      population: `Dân số ước tính khoảng 10.000 người.`,
      ethnic: `-	Xã có thành phần dân tộc đa dạng như Kinh, Êđê, M'Nông, Thái, Lào, Yarai, Tày, Nùng, Mường, Hoa, H'Rê, Dao, H'Mông, Khơ me cùng sinh sống. Tỉ lệ dân tộc thiểu số tại chỗ chiếm khoảng 21,9% dân số của xã. `,
      location: [
         `Phía Đông: giáp xã M’ Droh`,
         `Ph phía Tây: giáp xã Buôn Đôn`,
         `Phía Nam: giáp tỉnh Lâm Đồng, xã Ea Nuôl`,
         `Phía Bắc: giáp xã Buôn Đôn`,
      ],
      economy: `Nông nghiệp vẫn là ngành kinh tế chính của xã Ea Wer, với các loại cây trồng chủ lực như cà phê, hồ tiêu và điều. Nhờ đất đai màu mỡ và khí hậu thuận lợi, sản lượng nông sản của xã luôn đạt chất lượng cao, đáp ứng nhu cầu xuất khẩu.`,
      info: [
         `Với cảnh quan thiên nhiên hùng vĩ, bao gồm các con suối lớn và rừng nguyên sinh, xã Ea Wer đang phát triển các mô hình du lịch sinh thái. Các điểm đến như khu vực suối lớn giáp đất nông nghiệp thu hút du khách muốn khám phá thiên nhiên hoang sơ.`,
         ` Sự hòa quyện giữa các dân tộc Kinh, Ê-đê và M’nông tạo nên một bức tranh văn hóa phong phú. Các lễ hội truyền thống như cồng chiêng, lễ cúng bến nước vẫn được tổ chức thường xuyên, thu hút cả người dân và du khách.`,
      ],
   },
   {
      id: 7,
      province: 26,
      name: "Xã Ea Nuôl",
      image: ["ea-nuol-1.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, Quy mô dân số của xã mới Ea Nuôl, được hình thành từ việc sáp nhập các xã Ea Bar, Cuôr Knia và Ea Nuôl (huyện Buôn Đôn)`,
      square: `Diện tích tự nhiên khoảng 2.000 km², chủ yếu là đất nông nghiệp và lâm nghiệp.`,
      population: `Dân số ước tính khoảng 1.000 người.`,
      ethnic: `Bao gồm các dân tộc Kinh, Ê Đê, M'Nông, và một số dân tộc thiểu số khác. Cụ thể, xã Ea Nuôl được thành lập từ việc hợp nhất xã Ea Sáp, xã Cuôr Knia và một phần xã Ea Bar. Trước đây, các xã này đều có sự đa dạng về thành phần dân tộc, và việc sáp nhập này đã tạo nên một xã Ea Nuôl với sự đa dạng văn hóa, dân tộc. `,
      location: [
         `Phía Đông và Nam: giáp với thành phố Buôn Ma Thuột.`,
         `Phía Tây: giáp với tỉnh Lâm Đồng, xã Ea Wer `,
         `Phía Bắc: giáp với các xã M’Droh, xã Ea Wer`,
         `Phía Nam: xã Hòa Phú, phường Thành Nhất`,
      ],
      economy: [
         `Phát triển nông nghiệp hiện đại: Nông nghiệp vẫn là trụ cột kinh tế của xã Ea Nuôl, với các sản phẩm chủ lực như cà phê, hồ tiêu và cao su. Chính quyền đang khuyến khích người dân áp dụng công nghệ cao để tăng năng suất và chất lượng sản phẩm.`,
         `Hệ thống giao thông cải thiện: Các tuyến đường liên xã tại xã Ea Nuôl đã được nâng cấp, giúp việc đi lại giữa các thôn, buôn trở nên thuận tiện hơn. Đặc biệt, kết nối với quốc lộ 14 tạo điều kiện cho việc vận chuyển nông sản và hàng hóa.`,
      ],
      info: [
         `Bản sắc văn hóa phong phú: Với sự hiện diện của các dân tộc như Ê Đê, Kinh và Tày, xã Ea Nuôl là nơi lưu giữ nhiều lễ hội truyền thống như lễ cúng bến nước hay lễ hội đua voi. Những giá trị văn hóa này góp phần thu hút du khách và tạo nên dấu ấn riêng biệt.`,
         `Cảnh quan thiên nhiên đa dạng: Xã Ea Nuôl sở hữu những cánh đồng lúa trải dài, rừng nguyên sinh và các con sông thơ mộng. Khí hậu ôn hòa quanh năm là điều kiện lý tưởng để phát triển nông nghiệp và du lịch sinh thái.`,
      ],
   },
   {
      id: 8,
      province: 26,
      name: "Xã Ea Kiết",
      image: ["ea-kiet-1.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của xã Ea Kuêh và xã Ea Kiết thành xã mới có tên gọi là xã Ea Kiết.`,
      square: `Diện tích tự nhiên khoảng 9.055,02 ha, với đất sản xuất nông nghiệp chiếm 4.600,02 ha`,
      population: `Dân số khoảng 10.077 người, phân bố tại 13 thôn và buôn`,
      ethnic: `Xã Ea Kiết có cộng đồng dân cư đa dạng, bao gồm 8 dân tộc anh em, trong đó dân tộc thiểu số chiếm 452 hộ với 2.058 khẩu. Người Kinh chiếm khoảng 53,9%, người Ê Đê chiếm 36,42%, còn lại là các dân tộc như M’Nông, Tày.`,
      location: [
         `Phía Đông: giáp xã Ea Tul, xã Cư Pong`,
         `Phía Tây: giáp xã Buôn Đôn, xã Ea Sup`,
         `Ph phía Nam: giáp xã Cư M’gar, xã M’droh`,
         `Phía Bắc: giáp xã Ea Khai, xã Cư Pong, xã Ea Súp`,
      ],
      economy: `Là một xã thuần nông, kinh tế của Xã Ea Kiết chủ yếu dựa vào sản xuất nông nghiệp, chiếm 71% cơ cấu kinh tế địa phương. Các cây trồng chủ lực như cà phê, hồ tiêu, cao su và cây ăn quả`,
      info: `Xã Ea Kiết nổi bật với các giá trị văn hóa bản địa, đặc biệt là văn hóa cồng chiêng của người Ê Đê và các lễ hội truyền thống. `,
   },
   {
      id: 9,
      province: 26,
      name: "Xã Ea M'Droh",
      image: [`ea-mdrok-1.jpg`],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của các xã Quảng Hiệp, Ea M’nang và Ea M’Droh thành xã mới có tên gọi là xã Ea M’Droh.`,
      square: `Diện tích ước tính khoảng 220 km²`,
      population: `Dân số khoảng 28.000 người,`,
      ethnic: `Xã có cộng đồng dân cư đa dạng, bao gồm 8 dân tộc anh em, trong đó dân tộc thiểu số chiếm 452 hộ với 2.058 khẩu. Người Kinh chiếm khoảng 53,9%, người Ê Đê chiếm 36,42%, còn lại là các dân tộc như M’Nông, Tày.`,
      location: [
         `Phía Bắc: giáp xã Ea Kiết`,
         `Phía Nam: giáp các xã Ea Nuôl, xã Ea Wer, xã Quảng Phú`,
         `Phía Đông: giáp các xã Cư M'gar.`,
         `Phía phía Tây: giáp xã Ea Wer `,
      ],
      economy: [
         `Là một xã thuần nông, kinh tế của Xã Ea Kiết chủ yếu dựa vào sản xuất nông nghiệp, chiếm 71 % cơ cấu kinh tế địa phương.Các cây trồng chủ lực như cà phê, hồ tiêu, cao su và cây ăn quả`,
         `Xã Ea M’Droh nổi tiếng với các loại cây công nghiệp như cà phê, hồ tiêu và cao su, vốn là thế mạnh kinh tế của vùng Tây Nguyên`,
      ],
      info: `Với hơn 70% dân số là đồng bào dân tộc thiểu số, xã Ea M’Droh có tiềm năng phát triển du lịch cộng đồng thông qua các lễ hội truyền thống của người Êđê và trải nghiệm văn hóa tại các buôn làng.`,
   },
   {
      id: 10,
      province: 26,
      name: "Xã Quảng Phú",
      image: ["quang-phu-1.jpg", "quang-phu-2.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của thị trấn Quảng Phú, thị trấn Ea Pốk, xã Cư Suê và xã Quảng Tiến thành xã mới có tên gọi là xã Quảng Phú.`,
      square: `Diện tích: khoảng 150 km2`,
      population: `Dân số: khoảng 9.000 người `,
      ethnic: `Dân tộc chủ yếu là người Kinh ngoài ra còn có người Ê Đê và người Tày sinh sống.`,
      location: [
         `Phía Bắc: Giáp xã Cư M'gar xã Ea Tu`,
         `Phía Nam: Giáp phường Buôn Ma Thuột và phường Tân An`,
         `Phía Đông: Giáp xã Ea M’droh và xã Ea Nuôl`,
         `Phía Tây: Giáp xã Cuôr Đăng.`,
      ],
      economy: [
         `Sáp nhập làm tăng quy mô diện tích đất đai và dân số của xã mới, từ đó tạo ra tiềm năng phát triển kinh tế lớn hơn. `,
         `Có thể có sự đa dạng hóa các ngành nghề, lĩnh vực kinh tế, bao gồm cả nông nghiệp, công nghiệp, dịch vụ, tùy thuộc vào đặc điểm của các xã trước khi sáp nhập`,
      ],
      info: `Xã vẫn giữ gìn và phát huy những nét đặc sắc văn hóa bản địa, đặc biệt là các lễ hội truyền thống của người Ê Đê và M’nông, như lễ cúng bến nước, mừng lúa mới, múa cồng chiêng, và các nghi lễ mừng lúa mới.`,
   },
   {
      id: 11,
      province: 26,
      name: "Xã Cuôr Đăng",
      image: ["cuor-dang-1.jpg", "cuor-dang-2.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của xã Ea Drơng và xã Cuôr Đăng thành xã mới có tên gọi là xã Cuôr Đăng.`,
      square: `Diện tích: khoảng 180 km2 `,
      population: `Dân số: khoảng 20.000 người `,
      ethnic: `Đa dạng về thành phần dân tộc, bao gồm người Kinh, người Ê Đê, và các dân tộc thiểu số khác như M’nông. Trong đó, người Ê Đê và các dân tộc thiểu số chiếm khoảng 40% tổng dân số.`,
      location: [
         `Phía Bắc: Giáp xã Ea Tul`,
         `Phía Nam: Giáp xã Ea Knuêc và phường Tân An`,
         `Phía Đông: Giáp xã Chư bao và xã Krông Pắc`,
         `Phía Tây: Giáp xã Quảng Phú và xã Tân An.`,
      ],
      economy: `Nền kinh tế chủ yếu ở đây là nông nghiệp, đặc biệt là trồng các loại cây công nghiệp như cà phê, hồ tiêu và cao su . Ngoài ra, xã còn có tiềm năng phát triển du lịch sinh thái nhờ vào cảnh quan thiên nhiên và đất đỏ bazan màu mỡ  `,
      info: `Đặc sắc văn hóa nổi bật là nhà rông, một công trình kiến trúc truyền thống, và các lễ hội văn hóa của người Ê Đê.`,
   },
   {
      id: 12,
      province: 26,
      name: "Xã Cư M'gar",
      image: ["cu-mgar-1.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của các xã Ea H’đing, xã Ea Kpam và xã CưM’gar thành xã mới có tên gọi là xã Cư M’gar`,
      square: `Diện tích: khoảng 85 km2 `,
      population: `Dân số: 12.000 người`,
      ethnic: `Xã có nhiều dân tộc cùng sinh sống, trong đó có người dân tộc Kinh và các dân tộc thiểu số như Tày, Nùng và Ê Đê. `,
      location: [
         `Phía đông giáp xã Ea Tul `,
         `Phía tây giáp Ea M’Droh`,
         `Phía nam giáp xã Quảng Phú`,
         `Phía bắc giáp xã Ea Kiêt và xã Ea tul`,
      ],
      economy: [
         `Phát triển nông nghiệp bền vững: Xã có tiềm năng lớn trong phát triển nông nghiệp sạch và bền vững. Các mô hình trồng xen canh, như kết hợp cà phê với cây sầu riêng và bơ, đang được khuyến khích để tăng thu nhập cho người dân. `,
         `Tiềm năng du lịch sinh thái và văn hóa: Xã sở hữu hồ thủy lợi Buôn Joong và các suối tự nhiên, phù hợp để phát triển du lịch sinh thái. Các giá trị văn hóa bản địa, như không gian cồng chiêng và lớp học dệt thổ cẩm, là những điểm nhấn thu hút du khách. Các mô hình du lịch cộng đồng, như homestay tại các buôn đồng bào dân tộc thiểu số, đang được khuyến khích để tạo thêm việc làm và thu nhập cho người dân`,
      ],
      info: `Đặc sắc văn hóa rất đa dạng và đặc sắc, nổi bật với các lễ hội truyền thống, các nghề thủ công truyền thống và các phong tục tập quán của các dân tộc thiểu số. Trong đó, lễ hội Lồng Tồng của người tày, nùng, và lễ hội mừng lúa mới của người Xê Đăng là những sự kiện văn hóa tiêu biểu, thu hút du khách và góp phần quảng bá hình ảnh địa phương.`,
   },
   {
      id: 13,
      province: 26,
      name: "Xã Ea Tul",
      image: ["ea-tul-1.jpg", "ea-tul-2.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của các xã Ea Tar, Cư Dliê Mnông và Ea Tul thành xã mới có tên gọi là xã Ea Tul.`,
      square: `Diện tích: 158,37 km2`,
      population: `Dân số: khoảng 27.472 người `,
      ethnic: `Vẫn giữ nguyên thành phần dân tộc đa dạng như trước, với người Ê Đê và người Kinh là hai nhóm dân tộc chính. Người Ê Đê chiếm phần lớn dân số xã, giữ vai trò quan trọng trong đời sống văn hóa và kinh tế địa phương. Bên cạnh đó, còn có sự hiện diện của một số dân tộc thiểu số khác như Tày, Nùng, Thái.`,
      location: [
         `Phía Bắc giáp xã Cư Pong`,
         `Phía Nam giáp xã Cuôr Đăng và xã Cư Bao`,
         `Phía Đông giáp phường Buôn Hồ.`,
         `Phía Tây giáp xã CưMgar và xã Ea Kiết`,
      ],
      economy: [
         `Cây công nghiệp: Cà phê và hồ tiêu là hai cây trồng chủ lực, mang lại nguồn thu nhập chính cho người dân. `,
         `Phát triển mô hình: Xã khuyến khích các mô hình sản xuất nông nghiệp kết hợp, vừa trồng trọt vừa chăn nuôi để đa dạng hóa nguồn thu nhập. `,
         `Đất đai: Ea Tul có diện tích đất nông nghiệp rộng lớn, thuận lợi cho việc phát triển các loại cây trồng này. `,
      ],
      info: [
         `Xã Ea Tul là nơi sinh sống chủ yếu của người Ê Đê, do đó, văn hóa của dân tộc này được gìn giữ và phát huy. Các giá trị truyền thống như kiến trúc nhà dài, lễ hội, trang phục, ẩm thực, âm nhạc, và các nghi lễ tín ngưỡng vẫn còn được bảo tồn. `,
         `Cồng chiêng là một phần không thể thiếu trong đời sống văn hóa của người Ê Đê ở Ea Tul. Xã thường tổ chức các liên hoan văn hóa cồng chiêng, thu hút đông đảo nghệ nhân và thanh thiếu niên tham gia, góp phần truyền dạy và gìn giữ loại hình nghệ thuật này cho thế hệ trẻ.`,
         `Các lễ hội truyền thống của người Ê Đê như lễ mừng lúa mới, lễ cúng bến nước, và các lễ hội khác vẫn được duy trì và tổ chức thường xuyên tại các buôn làng. Đây là dịp để người dân thể hiện lòng biết ơn với thần linh, cầu mong một năm mới tốt lành và tăng cường tình đoàn kết cộng đồng.`,
      ],
   },
   {
      id: 14,
      province: 26,
      name: "Xã Pơng Drang",
      image: ["pong-drang-1.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của thị trấn Pơng Drang, xã Ea Ngai và xã Tân Lập thành xã mới có tên gọi là xã Pơng Drang. Xã được sáp nhập từ thị trấn Pơng Drang và xã Ea Ngai.`,
      square: `Diện tích: 358,7 km²`,
      population: `Dân số: 63.850 người`,
      ethnic: `Dân tộc chủ yếu là người Ê Đê và một số dân tộc thiểu số khác, cùng với người Kinh sinh sống.`,
      location: [
         `Phía Đông: Giáp xã Ea Dong, xã Krông Năng`,
         `Ph phía Tây: Giáp xã Cư Pong`,
         `Phía Nam: Giáp phường Buôn Hồ`,
         `Phía Bắc: Giáp xã Krông Buk`,
      ],
      economy: [
         `Xã đã chuyển dịch từ một xã thuần nông sang một mô hình phát triển đa dạng hơn, với các ngành phi nông nghiệp đóng góp đáng kể vào giá trị sản xuất. `,
         `Các tuyến đường giao thông, đặc biệt là đường trục chính nội đồng, đã được nâng cấp, giúp việc đi lại và vận chuyển hàng hóa thuận tiện hơn. `,
         `Xã Pơng Drang đang chuyển đổi từ canh tác truyền thống sang nông nghiệp công nghệ cao, với các loại cây trồng chủ lực như cà phê, hồ tiêu và cây ăn quả. Các chương trình hỗ trợ giống cây, kỹ thuật canh tác và vốn vay từ tỉnh giúp người dân nâng cao năng suất và giá trị nông sản.`,
         `Với cảnh quan thiên nhiên hùng vĩ, bao gồm đồi cà phê và các con suối nhỏ, Pơng Drang có tiềm năng lớn để phát triển du lịch sinh thái. Chính quyền xã khuyến khích các mô hình homestay, trải nghiệm văn hóa bản địa, tạo thêm thu nhập cho người dân.`,
      ],
      info: [
         `Các lễ hội truyền thống như Lễ hội cúng bến nước, Lễ hội mừng lúa mới, Lễ hội đâm trâu... vẫn được duy trì và tổ chức định kỳ, là dịp để người dân thể hiện bản sắc văn hóa và gắn kết cộng đồng.`,
         `Nghề dệt thổ cẩm, đan lát vẫn được duy trì, tuy nhiên, số lượng người làm có xu hướng giảm dần.`,
         `Nhà sàn truyền thống vẫn là hình ảnh quen thuộc ở Pơng Drang, tuy nhiên, một số gia đình đã bắt đầu xây dựng nhà kiên cố hơn.`,
      ],
   },
   {
      id: 15,
      province: 26,
      name: "Xã Krông Búk",
      image: ["krong-buk-1.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của xã Cư Né và xã Chứ Kbô thành xã mới có tên gọi là xã Krông Búk.`,
      square: `Diện tích: 62,95 km2 `,
      population: `Dân số: 7.957 người`,
      ethnic: `Dân tộc chủ yếu là người Kinh và người Ê đê, với hơn 65% là người Kinh.`,
      location: [
         `Phía Đông: Giáp xã Krông Năng, xã Dliê Ya.`,
         `Phía Tây: Giáp xã Cư Pong`,
         `Phía Nam: Giáp xã Pơng Drang.`,
         `Phía Bắc: Giáp xã Ea Khai `,
      ],
      economy: [
         `Cây trồng chủ lực: Cà phê là cây trồng chính, chiếm diện tích lớn và mang lại nguồn thu nhập quan trọng cho người dân. Việc áp dụng các tiêu chuẩn như 4C, Rainforest Alliance và VietGAP đã giúp nâng cao chất lượng cà phê và tăng thu nhập cho nông dân. `,
         `Các loại cây trồng khác: Ngoài cà phê, xã còn trồng các loại cây công nghiệp như cao su, tiêu, và cây ăn trái như sầu riêng, xoài, bưởi, …`,
         `Lâm nghiệp: Xã có diện tích rừng đáng kể với nhiều loại cây như keo, gõ, dầu đỏ, v.v.`,
         `Chăn nuôi: Phát triển: Chăn nuôi bò, heo, gia cầm được phát triển, góp phần đa dạng hóa sản phẩm nông nghiệp và tăng thu nhập cho người dân`,
         ` hội – Văn hóa – Lịch sử`,
      ],
      info: [
         `Bảo tồn và phát huy văn hóa truyền thống các lễ hội, phong tục tập quán, đặc biệt là lễ hội cồng chiêng, vẫn được duy trì và tổ chức thường xuyên, góp phần gìn giữ bản sắc văn hóa dân tộc.`,
         `Xã Krông Búk có sự đa dạng về thành phần dân tộc, điều này tạo nên một bức tranh văn hóa phong phú, đa màu sắc.`,
      ],
   },
   {
      id: 16,
      province: 26,
      name: "Xã Cư Pơng",
      image: ["cu-pong-1.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của xã Ea Sin và xã Cư Pơng thành xã mới có tên gọi là xã Cư Pơng.`,
      square: `Diện tích: khoảng 45 km2`,
      population: `Dân số: hơn 8.000 người`,
      ethnic: `Sau sáp nhập, với hơn 60% là người dân tộc Ê Đê và M’Nông. Sự đa dạng dân tộc tạo nên một cộng đồng đoàn kết, giàu bản sắc văn hóa.`,
      location: [
         `Phía Bắc giáp xã Ea Khai`,
         `Phía Đông giáp xã Krông Búk`,
         `Phía Nam giáp xã Ea Tul`,
         `Phía Tây giáp xã Ea Kiết, xã Ea Khai `,
      ],
      economy: [
         `Nông nghiệp và cây công nghiệp: Nông nghiệp vẫn là trụ cột kinh tế của xã Cư Pơng, với các loại cây trồng chủ lực như cà phê, hồ tiêu và cao su. Chính quyền địa phương đã hỗ trợ người dân áp dụng công nghệ tưới tiết kiệm và canh tác hữu cơ để tăng năng suất và bảo vệ môi trường.`,
         `Du lịch cộng đồng: Với cảnh quan thiên nhiên đẹp và văn hóa dân tộc phong phú, xã Cư Pơng đang phát triển các mô hình du lịch cộng đồng. Các lễ hội truyền thống như cồng chiêng, đâm trâu thu hút du khách, tạo thêm nguồn thu nhập cho người dân.`,
      ],
      info: [
         `Xã vẫn giữ gìn và phát huy những nét văn hóa đặc sắc của mình, đồng thời có thêm những nét văn hoa mới do sự giao thoa, hòa nhập.`,
         `Vùng đất Cư Prông sở hữu cảnh quan thiên nhiên độc đáo với sông, hồ và rừng nguyên sinh, rất phù hợp để phát triển du lịch sinh thái. Kết hợp với bản sắc văn hóa của các dân tộc thiểu số, xã có thể xây dựng các tour du lịch trải nghiệm, thu hút khách trong và ngoài nước. Một số khu du lịch cộng đồng đã bắt đầu hình thành tại đây.`,
      ],
   },
   {
      id: 17,
      province: 26,
      name: "Xã Ea Khăl",
      image: ["ea-khal-1.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của các xã Ea Nam, Ea Tir và Ea Khăl thành xã mới có tên gọi là xã Ea Khăl.`,
      square: `Diện tích: 247,05 km2 `,
      population: `Dân số: 29.956 người`,
      ethnic: `Hình thành một cộng đồng đa dạng với 19 dân tộc cùng sinh sống. Có sự đa dạng về thành phần dân tộc, với nhiều dân tộc thiểu số cùng sinh sống, trong đó có Ê Đê, M'Nông.  `,
      location: [
         `Phía Đông: Giáp xã Dliê Ya.`,
         `Phía Tây: Giáp xã Ea Sup`,
         `Phía Nam: Giáp xã Cư Pong, xã Krông Buk, xã Ea Kiết`,
         `Phía Bắc: Giáp xã Ea Wy và xã Ea Đrăng`,
      ],
      economy: [
         `Nông nghiệp là chủ đạo là cà phê, hồ tiêu, cao su và các loại cây công nghiệp khác là nguồn thu nhập chính của người dân. `,
         `Tiềm năng nông nghiệp công nghệ cao: Xã có điều kiện đất đai và khí hậu phù hợp để phát triển nông nghiệp theo hướng công nghệ cao, nâng cao năng suất và chất lượng sản phẩm`,
         `Bên cạnh nông nghiệp, chăn nuôi cũng là một ngành kinh tế tiềm năng, đặc biệt là các mô hình chăn nuôi bán công nghiệp. `,
         `Việc mở rộng giao thương, buôn bán nông sản và các dịch vụ khác cũng đang được chú trọng. `,
      ],
      info: [
         `Xã Ea Khăl lưu giữ nhiều giá trị văn hóa truyền thống của các dân tộc Ê Đê và M'Nông, thể hiện qua các lễ hội, phong tục tập quán và kiến trúc nhà ở.`,
         `Tiềm năng du lịch sinh thái và văn hóa: Cảnh quan thiên nhiên đa dạng, các buôn làng truyền thống và các lễ hội văn hóa là những yếu tố thu hút khách du lịch. `,
      ],
   },
   {
      id: 18,
      province: 26,
      name: "Xã Ea Drăng",
      image: ["ea-drang-1.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của thị trấn Ea Drăng, xã Ea Ral và xã Dliê Yang thành xã mới có tên gọi là xã Ea Drăng.`,
      square: `Diện tích: 171,34 km2`,
      population: `Dân số: khoảng 20.645 người`,
      ethnic: `Xã có đa dạng về thành phần dân tộc bao gồm Kinh, Tày, Ê Đê, Gia rai, Mường, Nùng, Thái, Dao, Mán, Ngái, Khơ Me, Hoa và Ba Na`,
      location: [
         `Phía Đông: Giáp xã Ea Hiao`,
         `Phía Tây: Giáp xã Ea Wy`,
         `Phía Nam: Giáp xã Ea Khai và xã Dliê Ya.`,
         `Phía Bắc: Giáp xã Ea H’leo`,
      ],
      economy: [
         `Nông nghiệp là chủ đạo: Cây trồng chủ lực là cà phê, hồ tiêu và lúa nước, đóng góp chính vào thu nhập của người dân. `,
         `Phát triển nông nghiệp công nghệ cao: Xã đang hướng tới ứng dụng công nghệ cao trong sản xuất nông nghiệp, như mô hình trồng chuối tiêu hồng nuôi cấy mô. `,
         `Tiềm năng phát triển công nghiệp và năng lượng tái tạo:Có quy hoạch phát triển khu công nghiệp và các dự án năng lượng tái tạo, tạo cơ hội thu hút đầu tư và việc làm. `,
      ],
      info: [
         `Lễ hội truyền thống: Các lễ hội truyền thống của các dân tộc vẫn được duy trì và tổ chức, như lễ cúng bến nước, lễ hội mừng lúa mới, lễ hội đâm trâu (tùy từng dân tộc), ... thu hút sự tham gia của đông đảo người dân.`,
         `Nghề thủ công truyền thống: Một số làng nghề truyền thống vẫn còn tồn tại, như dệt thổ cẩm, đan lát, làm rượu cần, ... được gìn giữ và phát huy.`,
         `Văn hóa ẩm thực: Ẩm thực tại Ea Drăng mang đậm dấu ấn của các dân tộc, với những món ăn đặc trưng như cơm lam, rượu cần, canh thụt, các loại đặc sản từ thịt thú rừng, cá suối, ...`,
         `Các nhạc cụ truyền thống như đàn đá, chiêng, cồng, sáo, kèn, ... được sử dụng trong các lễ hội và sinh hoạt văn hóa của cộng đồng.`,
      ],
   },
   {
      id: 19,
      province: 26,
      name: "Xã Ea Wy",
      image: ["ea-wy-1.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của các xã Cư A Mung, Cư Mốt và Ea Wy thành xã mới có tên gọi là xã Ea Wy.`,
      square: `Diện tích: 213,94 km2`,
      population: `Dân số: 28.657 người`,
      ethnic: `Dân tộc sinh sống bao gồm Ê Đê, Nùng, Tày, Mường, Kinh và một số dân tộc thiểu số khác.`,
      location: [
         `Phía Đông có thể giáp xã Ea Drăng`,
         `Phía Tây giáp xã Ea Rôk `,
         `Phía Nam giáp xã Ea Dliêya và Tam Giang `,
         `Phía Bắc giáp xã Ea H’leo và xã Ea Khai`,
      ],
      economy: [
         `Nông nghiệp: Cà phê, hồ tiêu và cao su là những cây trồng chủ lực, mang lại nguồn thu nhập chính cho người dân. `,
         `Xã có tiềm năng phát triển du lịch sinh thái nhờ cảnh quan thiên nhiên đa dạng, bao gồm các khu rừng nguyên sinh và suối. `,
         `Các lễ hội truyền thống của người Ê Đê và các hoạt động trải nghiệm văn hóa cũng là một điểm nhấn thu hút du khách. `,
         `Xã có tiềm năng phát triển năng lượng tái tạo, đặc biệt là điện gió, từ các dự án ở các khu vực lân cận. `,
      ],
      info: [
         `Lễ hội Thanh Minh của người Nùng An là một trong những lễ hội lớn, thu hút đông đảo người dân tham gia, thể hiện sự gắn kết cộng đồng và bản sắc văn hóa dân tộc. `,
         `Các nghề thủ công truyền thống như dệt thổ cẩm, đan lát vẫn được người dân gìn giữ và phát triển, góp phần bảo tồn văn hóa và tăng thêm thu nhập. `,
         `Xã có nguồn nhân lực dồi dào, đặc biệt là lực lượng lao động trẻ, đang được chú trọng đào tạo nghề, nâng cao tay nghề`,
      ],
   },
   {
      id: 20,
      province: 26,
      name: "Xã Ea Hiao",
      image: ["ea-hiao-1.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của xã Ea Sol và xã Ea Hiao thành xã mới có tên gọi là xã Ea Hiao.`,
      square: `Diện tích: 361,69 km²`,
      population: `Dân số: 30.796 người`,
      ethnic: `Dân tộc sinh sống chủ yếu là dân tộc Ê Đê, Mơ Nông và một số dân tộc khác.`,
      location: [
         `Phía Đông: Giáp ranh với tỉnh Gia Lai.`,
         `Phía Tây: Giáp các xã Ea H'leo và Ea Drăng`,
         `Phía Nam: Giáp các xã Ea Dliêya và Tam Giang.`,
         `Phía Bắc: Giáp ranh với tỉnh Gia Lai.`,
      ],
      economy: [
         `Nông nghiệp cây công nghiệp: Xã nổi tiếng với các loại cây công nghiệp như cà phê, hồ tiêu và cao su, vốn là nguồn thu nhập chính của người dân. Chính quyền hỗ trợ nông dân áp dụng kỹ thuật canh tác hiện đại, xây dựng thương hiệu sản phẩm như hạt mắc ca xuất khẩu sang Hàn Quốc, và mở rộng thị trường tiêu thụ để tăng giá trị kinh tế.`,
         `Phát triển thương mại nông thôn: Xã có vai trò quan trọng trong phát triển các khu chợ truyền thống và dịch vụ hỗ trợ nông nghiệp, như cung cấp giống cây trồng, phân bón và máy móc. Chính quyền khuyến khích người dân tham gia kinh doanh dịch vụ để đáp ứng nhu cầu địa phương và tạo thêm việc làm, góp phần thúc đẩy giao thương.`,
         `Phát triển nông nghiệp bền vững: Xã đang triển khai các mô hình nông nghiệp bền vững, như trồng sầu riêng theo tiêu chuẩn VietGAP và chăn nuôi sạch, với sự hỗ trợ từ các dự án như Yara Việt Nam. Các chương trình đào tạo kỹ thuật và hỗ trợ vốn vay giúp nông dân chuyển đổi từ canh tác truyền thống sang mô hình hiện đại, tăng năng suất và chất lượng sản phẩm.`,
      ],
      info: [
         `Lễ hội truyền thống thêm phần rực rỡ: Các lễ hội như nghi thức cúng bái của người Êđê hay các sự kiện văn hóa cộng đồng được tổ chức với quy mô lớn hơn, thu hút cả người dân địa phương và du khách. Những sự kiện này không chỉ bảo tồn văn hóa mà còn góp phần quảng bá du lịch và kinh tế.`,
         `Gìn giữ di sản dân tộc: Các làng nghề dệt thổ cẩm, chế tác nhạc cụ và làm gốm truyền thống được hỗ trợ để phát triển. Nhiều lớp học nghề đã được tổ chức, giúp thế hệ trẻ tiếp nối và lưu giữ những giá trị văn hóa độc đáo của xã.`,
         `Cộng đồng đoàn kết và hòa quyện: Sáp nhập đã mang các nhóm dân cư từ nhiều khu vực lại gần nhau, tạo nên một cộng đồng đa dạng nhưng gắn bó. Các hoạt động giao lưu văn hóa và hỗ trợ lẫn nhau đã giúp người dân Ea Sol xây dựng một cộng đồng bền vững.`,
      ],
   },
   {
      id: 21,
      province: 26,
      name: "Xã Krông Năng",
      image: ["krong-nang-1.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của thị trấn Krông Năng, xã Phú Lộc và xã Ea Hồ thành xã mới có tên gọi là xã Krông Năng.`,
      square: `-	Diện tích: khoảng 150 km²`,
      population: `-	Dân số: ước tính đạt hơn 30.000 người`,
      ethnic: `Xã Krông Năng là nơi sinh sống của các dân tộc Êđê, Tày, Nùng, Kinh và nhiều dân tộc khác.`,
      location: [
         `Phía Bắc: giáp với ranh với xã Dliê Ya và xã Krông Búk.`,
         `Phía Nam: giáp với với xã Phú Xuân và xã Ea Drông`,
         `Phía Đông:  giáp với ranh với xã Tam Giang `,
         `phía Tây: giáp với với xã Pơng Drang.`,
      ],
      economy: [
         `Nông nghiệp là ngành kinh tế chủ lực của xã Krông Năng, với các sản phẩm chủ lực như sầu riêng, cà phê và mắc ca. `,
         `Du lịch và dịch vụ: Với cảnh quan thiên nhiên đa dạng và sự phong phú về văn hóa của 31 dân tộc anh em, xã Krông Năng đang đẩy mạnh phát triển du lịch cộng đồng và sinh thái. Các điểm đến như hồ Ea Hồ, buôn văn hóa Êđê và các lễ hội truyền thống như Lễ hội văn hóa Việt Bắc tại xã Ea Tam thu hút đông đảo du khách.`,
      ],
      info: [
         ` dạng văn hóa dân tộc: Không gian văn hóa cồng chiêng Tây Nguyên, với 14 đội chiêng và 458 nghệ nhân, là di sản quý giá được bảo tồn và phát huy. Các lễ hội như Lễ cúng bến nước tại buôn Năng hay Lễ hội văn hóa Việt Bắc tại Ea Tam mang đậm bản sắc văn hóa địa phương.`,
         `Nghề thủ công truyền thống: Các nghề như dệt thổ cẩm, chế tác nhạc cụ và điêu khắc gỗ đang được khôi phục, tạo việc làm và thu nhập cho người dân. Những sản phẩm thủ công này không chỉ phục vụ đời sống mà còn trở thành quà lưu niệm hấp dẫn cho du khách.`,
      ],
   },
   {
      id: 22,
      province: 26,
      name: "Xã Dliê Ya",
      image: ["dlie-ya-1.jpg", "dlie-ya-2.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của các xã Ea Tóh, xã Ea Tân và xã Dliê Ya thành xã mới có tên gọi là xã Dliê Ya.`,
      square: `Diện tích: 182,53 km²`,
      population: `Dân số: 17.829 người`,
      ethnic: `Xã Dliê Ya là nơi sinh sống của các dân tộc Êđê, Tày, Nùng, Kinh và nhiều dân tộc khác.`,
      location: [
         `Phía Bắc: giáp với xã Ea Hiao và xã Ea Drăng và xã Ea khai`,
         `Phía Nam: giáp với xã Krông Năng`,
         `Phía Đông: giáp với xã Tam Giang `,
         `Phía Tây: giáp với xã Krông Búkvà xã Ea khai.`,
      ],
      economy_description: `Xã Dliê Ya với vị trí địa lý thuận lợi và nguồn tài nguyên phong phú, đang nổi lên như một trong những điểm sáng về phát triển kinh tế – xã hội của tỉnh Đắk Lắk. Dưới đây là những tiềm năng nổi bật:`,
      economy: [
         ` Phát triển nông nghiệp bền vững`,
         `Tiềm năng du lịch văn hóa và sinh thái`,
         ` Phát triển hạ tầng giao thông và đô thị`,
         `Đầu tư công nghiệp chế biến`,
         `Nguồn nhân lực và sự đồng lòng của cộng đồng`,
      ],
      info_description: `Xã Dliê Ya không chỉ là một địa danh mang đậm dấu ấn lịch sử mà còn sở hữu nhiều địa điểm hấp dẫn, thu hút du khách. Dưới đây là những địa điểm nổi bật:`,
      info: [
         `Khu căn cứ kháng chiến Cư Jut– Dliê Ya`,
         `Chùa Trung Hòa`,
         `Cảnh quan thiên nhiên xã Dliê Ya`,
         `Thác nước Ea Drăng`,
         `Làng nghề truyền thống của người Ê Đê`,
      ],
   },
   {
      id: 23,
      province: 26,
      name: "Xã Tam Giang",
      image: ["tam-giang-1.jpg", "tam-giang-2.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của các xã Ea Tam, Cư Klông và Tam Giang thành xã mới có tên gọi là xã Tam Giang.`,
      square: `Diện tích: 197,9 km²`,
      population: `Dân số: 18.715 người`,
      ethnic: `Xã có thành phần dân tộc đa dạng, bao gồm cả dân tộc Kinh và các dân tộc thiểu số. Trong đó, các dân tộc thiểu số tại chỗ như Ê Đê, M'Nông, và các dân tộc khác cũng sinh sống tại đây`,
      location: [
         `Phía Bắc: giáp với xã Ea Hiao và xã Dilê Ya`,
         `Phía Tây: giáp với xã Krông Năng và xã Dilê Ya`,
         `Ph phía Nam: giáp với xã Krông Năng và xã Phú Xuân `,
         `Phía Đông: giáp với tỉnh Gia Lai và xã Ea Knốp `,
      ],
      economy: [
         `Nông nghiệp là ngành kinh tế chủ đạo, với các cây trồng chính là cà phê, hồ tiêu, và lúa nước.`,
         `Một số hộ gia đình tham gia vào chăn nuôi gia súc, gia cầm.`,
         `Hoạt động thương mại, dịch vụ còn hạn chế.`,
      ],
      info: [
         `Mang đậm nét văn hóa của người Ê Đê.`,
         `Có các lễ hội truyền thống như lễ hội mừng lúa mới, lễ hội cúng sức khỏe.`,
         `Nhà dài là kiến trúc truyền thống đặc trưng.`,
         `Cồng chiêng và các nhạc cụ truyền thống khác đóng vai trò quan trọng trong đời sống văn hóa.`,
         `Nghề thủ công truyền thống như dệt thổ cẩm, đan lát vẫn được duy trì.`,
         `Tín ngưỡng, phong tục tập quán của người Ê Đê vẫn còn được bảo tồn`,
      ],
   },
   {
      id: 24,
      province: 26,
      name: "Xã Phú Xuân",
      image: ["phu-xuan-1.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của các xã Ea Púk, Ea Dăh và Phú Xuân thành xã mới có tên gọi là xã Phú Xuân.`,
      square: `Diện tích: 4.524 ha`,
      population: `Dân số: 19.350 người. `,
      ethnic: `Trên địa bàn xã có 18 dân tộc cùng sinh sống, chủ yếu là dân tộc Kinh, các dân tộc thiểu số khác khoảng 4,7% dân số.`,
      location: [
         `Phía Bắc: giáp với xã Krông Năng và xã Tam Giang `,
         `Phía Nam: giáp với xã Ea Kar`,
         `Phía Đông: giáp với xã Ea Knốp`,
         `Phía Tây: iáp xã Krông Năng và xã Ea Drông`,
      ],
      economy: [
         `Kinh tế của xã Phú Xuân chủ yếu dựa vào nông nghiệp, với các sản phẩm chủ lực như cà phê, hồ tiêu, và sầu riêng – một loại cây trồng đang được chú trọng phát triển tại huyện Krông Năng. Ngoài ra, chăn nuôi gia súc và gia cầm cũng đóng vai trò quan trọng trong việc đa dạng hóa nguồn thu nhập của người dân.`,
         `Với cảnh quan thiên nhiên đặc trưng của vùng cao nguyên và sự đa dạng văn hóa của các dân tộc sinh sống tại đây, xã Phú Xuân có tiềm năng phát triển du lịch nông thôn. Các hoạt động như tham quan vườn cây ăn quả, trải nghiệm văn hóa địa phương, và khám phá các lễ hội truyền thống có thể thu hút du khách trong và ngoài tỉnh. Đây là hướng đi đầy triển vọng để nâng cao đời sống người dân và quảng bá hình ảnh xã Phú Xuân.`,
      ],
      info: [
         `Xã Phú Xuân đã được UBND tỉnh công nhận là xã đạt chuẩn Nông thôn mới; hiện nay xã đang phấn đấu xây dựng xã Phú Xuân là Đô thị loại V đến năm 2030. `,
         `Cơ sở hạ tầng chính: Giáo dục: Trên địa bàn xã có 1 trường THPT Lý Tự Trọng và 07 trường học Mầm non, Tiểu học, THCS công lập và một số cơ sở giáo dục mầm non ngoài công lập khác, đáp ứng tốt công tác giáo dục trên địa bàn xã và phục vụ các khu vực lân cận`,
      ],
   },
   {
      id: 25,
      province: 26,
      name: "Xã Krông Pắc",
      image: ["krong-pac-1.jpg", "krong-pac-2.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của thị trấn Phước An và các xã Hòa An (huyện Krông Pắc), Ea Yông, Hòa Tiến thành xã mới có tên gọi là xã Krông Pắc.`,
      square: `Diện tích: khoảng 110 km²`,
      population: `Dân số: ước tính khoảng 9.000-11.000 người`,
      ethnic: `Dân cư tại xã Krông Pắc chủ yếu là người dân tộc Kinh, với một phần dân tộc Êđê, Tày, Nùng, và M’nông sinh sống. `,
      location: [
         `Phía Bắc: giáp với phường Cư Bao và xã Cuôr Đăng`,
         `Phía Nam: giáp với Ea Ning và xã Tân Tiến `,
         `phía Đông: giáp với xã Ea Phê và xã Tân Tiến `,
         `Phía Tây: giáp với xã Ea Knuếc và xã Cuôr Đăng`,
      ],
      economy: `Xã Krông Pắc có lợi thế về đất bazan màu mỡ, phù hợp với các loại cây trồng chủ lực như sầu riêng, cà phê, hồ tiêu, và cao su. Đặc biệt, sầu riêng Krông Pắc đã trở thành thương hiệu nổi tiếng, với sản lượng hơn 80.000 tấn trong niên vụ 2023, mang lại giá trị kinh tế cao và thúc đẩy phát triển nông nghiệp bền vững.`,
      info: `Xã Krông Pắc có văn hoá đa dạng, vừa mang đặc trưng của các dân tộc bản địa Tây Nguyên, vừa chịu ảnh hưởng đậm nét của người Kinh di cư. Nét đặc trưng nổi bật là văn hoá cồng chiêng, nhà dài, tín ngưỡng đa thần và các lễ hội gắn với nông nghiệp.`,
   },
   {
      id: 26,
      province: 26,
      name: "Xã Ea Knuếc",
      image: ["ea-knuec-1.jpg", "ea-knuec-2.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của các xã Hòa Đông, Ea Kênh và Ea Knuếc thành xã mới có tên gọi là xã Ea Knuếc.`,
      square: `Diện tích: 27,66 km²`,
      population: `Dân số: 13.100 người`,
      ethnic: `Chủ yếu là người Kinh, bên cạnh đó có cộng đồng Ê Đê, M’nông, Tày, Nùng di cư từ các tỉnh phía Bắc.`,
      location: [
         `Phía Đông: Giáp với xã Krông Pắc`,
         `Phía Tây: Giáp với phường Tân an và phường Tân Lập`,
         `Phía Nam: Giáp với Ea ktur và xã Ea Ning `,
         `Phía Bắc: Giáp với xã Cuôr Đăng và phường Tân An`,
      ],
      economy: [
         `Kinh tế xã Ea Knuếc phát triển dựa trên nông nghiệp, đặc biệt là: cà phê, hồ tiêu, sầu riêng, bơ. Chăn nuôi bò, heo, gia cầm phát triển ở quy mô hộ gia đình. Một số hộ có mô hình trồng xen canh cà phê – hồ tiêu – cây ăn quả, đa dạng hoá sản phẩm.`,
         `Kinh tế dịch vụ, thương mại nhỏ lẻ phục vụ đời sống dân sinh (chợ xã, cửa hàng vật tư nông nghiệp).`,
      ],
      info: [
         `Xã có nhiều buôn đồng bào Ê Đê, vẫn còn lễ hội mừng lúa mới, cồng chiêng, lễ cúng bến nước.`,
         `Một số gia đình vẫn dựng nhà dài Ê Đê, tuy nhiên xu hướng này giảm dần do quá trình đô thị hoá.`,
         `Các nghi lễ tín ngưỡng và nghệ thuật dân gian như hát kể sử thi, kể khan, đánh chiêng, múa dân gian… còn được duy trì qua các dịp lễ, Tết.`,
         `Văn hoá cộng đồng gắn chặt với canh tác nương rẫy và lễ hội mùa vụ.`,
      ],
   },
   {
      id: 27,
      province: 26,
      name: "Xã Tân Tiến",
      image: ["tan-tien-1.jpg", "tan-tien-2.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của các xã Ea Yiêng, Ea Uy và Tân Tiến thành xã mới có tên gọi là xã Tân Tiến.`,
      square: `Diện tích: 37 km2`,
      population: `Dân số: 11.845 người.`,
      ethnic: [
         `Chủ yếu là người Kinh di cư đến khai hoang lập nghiệp từ thập niên 1980.`,
         `Có cộng đồng Ê Đê, M’nông, Tày, Nùng…`,
         `Đặc điểm dân cư đa số là hộ nông dân, lao động sản xuất nông nghiệp.`,
      ],
      location: [
         `Phía đông: giáp với xã Vụ Bổn `,
         `Phía tây: giáp với xã xã Krông Pắc và xã Ea Ning `,
         `Phía nam: giáp với xã Dang Kang`,
         `Phía bắc: giáp với xã ea phê và xã krông pắc`,
      ],
      economy: [
         `Xã Tân Tiến phát triển mạnh về nông nghiệp hàng hóa: Cà phê, phát triển xen canh hồ tiêu, sầu riêng, bơ, mở rộng diện tích do giá trị kinh tế cao. Một số hộ trồng cây công nghiệp ngắn ngày, cây lương thực, rau màu.`,
         `Chăn nuôi gia súc, gia cầm quy mô hộ gia đình, phục vụ tiêu dùng nội địa và chợ đầu mối.`,
         `Các dịch vụ thương mại, vật tư nông nghiệp phát triển theo mô hình kinh tế hộ.`,
      ],
      info: [
         `Văn hóa cộng đồng mang đậm nét của người Kinh vùng Tây Nguyên: đoàn kết, cần cù lao động, gắn bó với đất đai.`,
         `Các lễ hội dân gian đặc trưng vùng bản địa như lễ hội mừng lúa mới, cồng chiêng có mặt ở một số cụm dân cư Ê Đê – tuy nhiên không đậm đặc như các buôn thuần Ê Đê.`,
      ],
   },
   {
      id: 28,
      province: 26,
      name: "Xã Ea Phê",
      image: ["ea-phe-1.jpg", "ea-phe-2.jpg"],
      introduce: `Sắp xếp toàn bộ diện tích tự nhiên, quy mô dân số của các xã Ea Kuăng, Ea Hiu và Ea Phê thành xã mới có tên gọi là xã Ea Phê.`,
      square: `Diện tích: 44,52 km²`,
      population: `Dân số: 23. 488 người`,
      ethnic: [
         `Chủ yếu là người Kinh (chiếm hơn 80%).`,
         `Ngoài ra có cộng đồng Ê Đê, Tày, Nùng, đa số di cư từ miền Bắc `,
      ],
      location: [
         `Phía Bắc: giáp với với xã Ea Drông và phường Cư Bao `,
         `Phía Nam: giáp với với xã Tân tiến và xã Vụ Bổn `,
         `Phía Đông: giáp với với Ea Kly`,
         `ía Tây: giáp với với xã Krông Pắc`,
      ],
      economy: [
         `Kinh tế chủ lực là nông nghiệp hàng hóa, đặc biệt: Cà phê, Hồ tiêu, sầu riêng, bơ.`,
         `Dịch vụ, thương mại nhỏ lẻ: vật tư nông nghiệp, chế biến cà phê, thu mua nông sản.`,
      ],
      info: [
         `Một số buôn còn tổ chức lễ hội mừng lúa mới, cồng chiêng, lễ cúng bến nước, thường tập trung ở các cụm dân cư Ê Đê.`,
         `Xã Ea Phê là xã nông thôn mới, đạt tiêu chí hạ tầng cơ bản, có phong trào xây dựng đời sống văn hoá cơ sở tốt.`,
      ],
   },

   {
      id: 80,
      province: 26,
      name: "Xã Xuân Phước",
      image: ["xuan-phuoc-1.jpg"],
      introduce: `Xã Xuân Phước được thành lập từ việc sáp nhập xã Xuân Quang 3 và xã Xuân Phước.`,
      square: `Diện tích: 102,81 km² `,
      population: `Dân số: khoảng 16.000 người.`,
      ethnic: `Xã Xuân Phước là nơi sinh sống của nhiều dân tộc khác nhau, chủ yếu là người Kinh và một số dân tộc thiểu số khác: Ê Đê, Ba Na, Tày....`,
      location: [
         `Phía Đông: Xã Tuy An Tây`,
         `Phía Tây: Xã Tây Sơn, xã Phú Mỡ`,
         `Phía Nam: Giáp xã Vân Hòa.`,
         `Phía Bắc: Giáp xã Đồng Xuân.`,
      ],
      economy: [
         `Nông nghiệp: Với diện tích đất nông nghiệp lớn, Xuân Phước tập trung phát triển các loại cây trồng chủ lực như lúa nước, sắn và cây công nghiệp ngắn ngày. Xã cũng đang áp dụng các mô hình nông nghiệp hiện đại, như canh tác hữu cơ và liên kết sản xuất với các doanh nghiệp để nâng cao giá trị sản phẩm nông nghiệp.`,
         `Phát triển ngành nghề thủ công: Người dân Xuân Phước có truyền thống làm các sản phẩm thủ công như đan lát và chế biến thực phẩm truyền thống. Những sản phẩm này không chỉ phục vụ nhu cầu nội địa mà còn có tiềm năng xuất khẩu, góp phần tăng thu nhập cho người dân.`,
         `Du lịch: Với cảnh quan thiên nhiên xanh mát và các di tích lịch sử, Xuân Phước có tiềm năng phát triển du lịch nông thôn. Các mô hình trải nghiệm như tham quan làng nghề, tham gia sản xuất nông nghiệp hoặc khám phá các di tích lịch sử đang được khuyến khích để thu hút du khách.`,
      ],
      info_description: `Người dân Xuân Phước vẫn duy trì các phong tục tập quán lâu đời, như các lễ hội cúng thần nông, lễ hội đình làng và các hoạt động văn hóa dân gian. Những lễ hội này không chỉ mang ý nghĩa tâm linh mà còn góp phần gắn kết cộng đồng, tạo nên không khí vui tươi và đoàn kết.`,
      info: [
         `Các di sản văn hóa, địa danh tiêu biểu: Hồ Phú Xuân, đập Suối Cối, sông Trà Bương, chùa Từ Tâm, Viên Lâm, nhà thờ Đồng Tre và Niệm Phật Đường Hòa Quang,…`,
         `Các món ăn và đặc sản: Bánh canh hẹ, bánh xèo, gỏi cá mai, và các món hải sản tươi sống như sò huyết, cá ồ,…`,
      ],
   },
   {
      id: 81,
      province: 26,
      name: "Xã Đồng Xuân",
      image: ["dong-xuan-1.jpg"],
      introduce: `Xã Đồng Xuân được thành lập từ việc sáp nhập thị trấn La Hai và các xã Xuân Sơn Nam, Xuân Sơn Bắc, Xuân Long, Xuân Quang 2.`,
      square: `Diện tích: 206,26 km² `,
      population: `Dân số: khoảng 27.000 người.`,
      ethnic: `Xã Xuân Phước là nơi sinh sống của nhiều dân tộc khác nhau, chủ yếu là người Kinh và một số dân tộc thiểu số khác: Ba Na, Chăm, ...`,
      location: [
         `Phía Đông: Giáp xã Tuy An Tây`,
         `Phía Tây: Giáp xã Tây Sơn, xã Phú Mỡ`,
         `Phía Nam: Giáp xã Xuân Phước, xã Tuy An Tây`,
         `Phía Bắc: Giáp xã Xuân lãnh, Xuân Thọ `,
      ],
      economy: [
         ` lịch sinh thái và văn hóa: Với địa hình đồi núi và ven biển, xã Đồng Xuân có nhiều cảnh quan thiên nhiên hoang sơ và các lễ hội văn hóa truyền thống.`,
         `Nông nghiệp công nghệ cao: Diện tích đất rộng lớn xã triển khai các mô hình nông nghiệp ứng dụng công nghệ cao.`,
         `Công nghiệp: Phát triển các khu công nghiệp nhỏ, tận dụng vị trí gần cảng biển để thu hút các doanh nghiệp sản xuất và chế biến.`,
         `Phát triển cộng đồng bền vững: Tập trung vào các chương trình giáo dục, y tế và hỗ trợ sinh kế.`,
      ],
      info_description: `Xã Đồng Xuân có đông đồng bào dân tộc thiểu số sinh sống từ lâu đời, với nhiều nét văn hoá đặc trưng và các nghề thủ công truyền thống, làm ra những sản phẩm độc đáo và hữu dụng. Điển hình là nghề đan đát của đồng bào Ba Na, Chăm Hroi (một nhánh của dân tộc Chăm), mang đậm dấu ấn văn hóa dân tộc. Trải qua nhiều thế hệ, nghề truyền thống này vẫn được bảo tồn và phát triển.`,
      info: [
         `Các di sản văn hóa, địa danh tiêu biểu: Khu di tích lịch sử quốc gia Nơi thành lập Chi bộ Đảng Cộng sản đầu tiên ở Phú Yên, suối nước nóng Triêm Đức,…`,
         `Các món ăn và đặc sản: Thịt lợn bản, heo rừng, gà nương, các loại măng và nấm rừng,…`,
      ],
   },
   {
      id: 82,
      province: 26,
      name: "Phường Buôn Ma Thuột",
      image: ["buon-ma-thuot-1.jpg"],
      introduce: `Phường Buôn Ma Thuột được thành lập từ việc sáp nhập các phường Thành Công, Tân Tiến, Tân Thành, Tự An, Tân Lợi và xã Cư Êbur.`,
      square: `Diện tích: 71,99 km² `,
      population: `Dân số: Khoảng 169.000 người, là khu vực có số dân đông nhất trong các đơn vị hành chính cấp xã của tỉnh Đắk Lắk.`,
      ethnic: `Phường Buôn Ma Thuột là nơi sinh sống của nhiều dân tộc khác nhau, chủ yếu là người Kinh, Ê Đê và một số dân tộc thiểu số khác. Người Ê Đê sống tập trung tại các buôn như buôn Akô Dhông, buôn Ea Bông, buôn Păn Lăm…`,
      location: [
         `Phía Bắc: Giáp xã Quảng Phú, xã Ea Nuool, phường Tân An`,
         `Phía Nam: Giáp với phường Tân Lập của thành phố Buôn Ma Thuột.`,
         `Phía Đông: Giáp với phường Tân An`,
         `Phía Tây: Giáp với xã Ea Nuôl`,
      ],
      economy_description: `Với hệ thống giao thông hiện đại và các tuyến đường huyết mạch giúp phường trở thành trung tâm kinh tế, văn hóa và logistics của khu vực. Các ngành kinh tế chủ lực như cà phê, thương mại, dịch vụ và du lịch đang được chú trọng để khai thác tối đa tiềm năng của phường.`,
      economy: [
         `Ngành cà phê: Phường Buôn Ma Thuột nằm trong vùng đất bazan màu mỡ, nơi sản xuất cà phê nổi tiếng thế giới. Với hơn 175.000 ha diện tích cà phê trên toàn tỉnh, phường là trung tâm của các hoạt động chế biến, xuất khẩu và xây dựng thương hiệu “Cà phê Buôn Ma Thuột”. `,
         `Phát triển thương mại và dịch vụ: Sự gia tăng dân số và cải thiện hạ tầng giao thông đã thúc đẩy các hoạt động thương mại, dịch vụ tại phường. Các trung tâm thương mại, chợ truyền thống và cơ sở kinh doanh nhỏ lẻ đang phát triển mạnh mẽ, đáp ứng nhu cầu của người dân và du khách.`,
         `Du lịch văn hóa và sinh thái: Với nhiều di tích lịch sử, văn hóa và các điểm du lịch sinh thái, nghỉ dưỡng được đầu tư, tạo sức hút cho du khách và định hình du lịch ngày càng phát triển của phường.`,
      ],
      info_description: `Dân cư tại phường là sự kết hợp đa dạng giữa các dân tộc Kinh, Ê Đê, và các dân tộc thiểu số khác, tạo nên một cộng đồng văn hóa phong phú, với nhiều phong tục, tập quán và lễ hội truyền thống đặc sắc.`,
      info: [
         {
            des: `Các lễ hội truyền thống:`,
            list: [
               `Lễ hội Cà phê Buôn Ma Thuột: Là một sự kiện lớn được tổ chức định kỳ, tôn vinh ngành cà phê và quảng bá du lịch. Lễ hội bao gồm các hoạt động như triển lãm, hội thảo, và biểu diễn nghệ thuật.`,
               `Không gian văn hóa cồng chiêng Tây Nguyên: Được UNESCO công nhận là di sản phi vật thể, không gian cồng chiêng Tây Nguyên là một điểm nhấn văn hóa quan trọng, thu hút du khách tìm hiểu về truyền thống của các dân tộc bản địa.`,
               `Các lễ hội truyền thống của người dân tộc thiểu số: Mặc dù các lễ hội này thường được tổ chức ở các buôn làng, ảnh hưởng lớn đến đời sống văn hóa của người dân Buôn Ma Thuột, đặc biệt là trong việc bảo tồn và phát huy các giá trị văn hóa truyền thống.`,
            ],
         },
         {
            des: `Các di sản văn hóa, địa danh tiêu biểu:`,
            list: [
               `Kiến trúc nhà dài truyền thống: Nhà dài là biểu tượng của văn hóa Ê Đê, thể hiện cấu trúc gia đình mẫu hệ và đời sống cộng đồng.`,
               `Các di tích lịch sử và văn hóa: Phường Buôn Ma Thuột có nhiều di tích lịch sử, văn hóa như Nhà đày Buôn Ma Thuột, Bảo tàng Đắk Lắk, Tượng đài Chiến thắng Buôn Ma Thuột, chùa sắc tứ Khải Đoan, bảo tàng thế giới cà phê và các buôn làng cổ, nơi lưu giữ những giá trị văn hóa truyền thống của vùng đất Tây Nguyên.`,
            ],
         },
         {
            des: `Các món ăn và đặc sản: Bún đỏ, bún chìa, bánh ướt chồng đĩa,  lẩu cá lăng, gỏi cà đắng cá cơm, canh thụt đọt mây, cá suối nướng, rượu cần, đặc biệt là cà phê Buôn Ma Thuột,…`,
         },
      ],
   },

   {
      id: 83,
      province: 26,
      name: "Phường Tân An",
      image: ["tan-an-1.jpg"],
      introduce: `Phường Tân An được thành lập từ việc sáp nhập phường Tân An (cũ), xã Ea Tu và xã Hòa Thuận.`,
      square: `Diện tích: 56,41 km² `,
      population: `Dân số: Khoảng 64.000 người.`,
      ethnic: `Phường Tân An là nơi sinh sống của nhiều dân tộc khác nhau, chủ yếu là người Kinh, Ê Đê và một số dân tộc thiểu số khác: Tày, Nùng …`,
      location: [
         `Phía đông: Giáp xã Ea Knuếc`,
         `Phía tây: Giáp Phường Buôn Ma Thuột`,
         `Phía nam: Giáp Phường Tân Lập`,
         `Phía bắc: Giáp xã Quảng Phú, xã Cuôr Đăng`,
      ],
      economy_description: `Với hệ thống giao thông hiện đại và các tuyến đường huyết mạch: Quốc lộ 14, Quốc lộ 26, đường tránh Đông, đường tránh Tây tạo thuận lợi cho hoạt động phát triển kinh tế và logistics của khu vực. Các ngành kinh tế chủ lực như công nghiệp, thương mại, dịch vụ, nông nghiệp đang được chú trọng để khai thác tối đa tiềm năng của phường.`,
      economy: [
         `Nghành công nghiệp: Cụm khu công nghiệp Tân An với diện tích 104,75 ha, với cơ sở hạ tầng được đầu tư nâng cấp, tạo điều kiện thuận lợi cho việc vận chuyển hàng hóa, thu hút nhiều dự án đầu tư, đặc biệt trong lĩnh vực công nghiệp chế biến nông sản, sản xuất công nghiệp, góp phần tăng trưởng kinh tế địa phương.`,
         `Sản xuất nông nghiệp: Phường Tân An với thổ nhưỡng đất đai màu mỡ, có thế mạnh phát triển các loại cây công nghiệp: Cà phê, cao su, hồ tiêu và cây ăn trái. `,
         `Phát triển đô thị, thương mại và dịch vụ: Phường Tân An được quy hoạch và phát triển với nhiều khu đô thị hiện đại: Khu đô thị mới EcoCity Premia, Khu đô thị mới Ân Phú, Khu đô thị mới Hiệp Phúc,… bên cạnh đó là hệ thống các tiện ích xã hội: siêu thị, chợ, khách sạn, bệnh viện, trường học,… tạo động lực cho phát triển kinh tế của phường. `,
      ],
      info_description: `Với cộng đồng dân cư đa dạng, bao gồm người Kinh và các dân tộc thiểu số như Ê Đê, Tày, Nùng, tạo nên sự giao thoa văn hóa phong phú và đặc sắc, đặc biệt là văn hóa Ê Đê`,
      info: [
         `Các lễ hội truyền thống: Các lễ hội như Ngày hội Văn hóa dân tộc, trình diễn cồng chiêng, múa dân gian được tổ chức và bảo tồn. `,
         `Các di sản văn hóa, địa danh tiêu biểu: Làng cà phê Trung Nguyên nơi thưởng thức hương vị cà phê độc đáo và là điểm chiêm ngưỡng không gian đặc sắc, đậm đà bản sắc Tây Nguyên. `,
         `Các món ăn và đặc sản: Cà đắng giã lá é, đậu non giã gừng, cá nục giã ớt sừng, cà phê, …`,
      ],
   },
   {
      id: 84,
      province: 26,
      name: "Phường Tân Lập ",
      image: ["tan-lap-1.jpg"],
      introduce: `Phường Tân Lập được thành lập từ việc sáp nhập các phường Tân Lập (cũ), Tân Hòa và xã Hòa Thắng.`,
      square: `Diện tích: 46,70 km² `,
      population: `Dân số: Khoảng 73.000 người.`,
      ethnic: `Phường Tân Lập là nơi sinh sống của nhiều dân tộc khác nhau, chủ yếu là người Kinh, Ê Đê và một số dân tộc thiểu số khác: Tày, Nùng …`,
      location: [
         `Phía bắc: giáp phường Tân An`,
         `Phía đông: giáp xã Ea Knếc, xã Ea Ktur`,
         `Phía tây: giáp phường Buôn Ma Thuột `,
         `Phía nam: giáp xã Ea Ktur, xã Ea Kao`,
      ],
      economy_description: `Với hệ thống giao thông hiện đại và các tuyến đường huyết mạch: Quốc lộ 26, Quốc lộ 27, Đại lộ Đông Tây, đặc biệt là Cảng hàng không Buôn Ma Thuột tạo thuận lợi cho phát triển kinh tế và logistics của khu vực. Các ngành kinh tế chủ lực như dịch vụ du lịch, nông nghiệp đang được chú trọng để khai thác tối đa tiềm năng của phường.`,
      economy: [
         `Dịch vụ du lịch: Khu du lịch sinh thái cộng đồng Kŏ Tam với vẻ đẹp mộc mạc, sâu lắng, đặc sắc tinh thần đại ngàn và văn hóa Ê Đê; Các Homestay nghĩ dưỡng bên hồ Ea Cuôr Kap với không gian yên bình, thoáng mát của thiên nhiên Tây Nguyên,… Du lịch cộng đồng dựa trên với vẻ đẹp thiên nhiên và văn hóa của các dân tộc thiểu số, tạo sự trải nghiệm về đời sống, phong tục của người dân địa phương.`,
         `Sản xuất nông nghiệp: Phường có Trung Tâm Cây Giống Viện EaKmat nơi giống cây công nghiệp, cây ăn trái chất lượng của vùng. Cùng với diện tích đất nông nghiệp rộng lớn, màu mỡ phường có tiềm năng phát triển nông nghiệp công nghệ cao, đặc biệt là cà phê và sầu riêng. `,
      ],
      info_description: `Với cộng đồng dân cư đa dạng, bao gồm người Kinh và các dân tộc thiểu số như Ê Đê, Tày, Nùng. Văn hóa Ê Đê có thể là một yếu tố quan trọng, với các lễ hội truyền thống, làng nghề thủ công`,
      info: [
         `Các lễ hội truyền thống: Các lễ hội truyền thống của dân tộc thiểu số luôn được tổ chức và bảo tồn.`,
         `Các di sản văn hóa, địa danh tiêu biểu: Khu du lịch sinh thái cộng đồng Kŏ Tam, hồ Ea Cuôr Kap, Chợ đầu mối Tân Hòa,... `,
         `Các món ăn và đặc sản: gà nướng cơm lam, heo rừng nướng ống tre, các món rau rừng, Sầu riêng, …`,
      ],
   },
   {
      id: 85,
      province: 26,
      name: "Phường Thành Nhất",
      image: ["thanh-nhat-1.jpg"],
      introduce: `Phường Thành Nhất được thành lập từ việc sáp nhập các phường Thành Nhất (cũ) và phường Khánh Xuân.`,
      square: `Diện tích: 32,22 km² `,
      population: `Dân số: Khoảng 52.000 người.`,
      ethnic: `Phường Thành Nhất là nơi sinh sống của nhiều dân tộc khác nhau, chủ yếu là người Kinh, Ê Đê và một số dân tộc thiểu số khác.`,
      location: [
         `Phía đông giáp phường Ea Kao và phường Buôn Ma Thuột.`,
         `Phía tây giáp xã Hòa Phú `,
         `Phía nam giáp xã Hòa Phú `,
         `Phía bắc giáp xã Ea Nuôl và phường Buôn Ma Thuột.`,
      ],
      economy_description: `Với hệ thống giao thông phát triển và các tuyến đường huyết mạch: Quốc lộ 14, đường tránh Tây tạo thuận lợi cho giao thương. Kinh tế chủ lực của phường là thương mại dịch vụ và nông nghiệp.`,
      economy: [
         `Thương mại và dịch vụ: Các hệ thống siêu thị và chợ truyền thống phát triển mạnh mẽ, tạo động lực phát triển thương mại, buôn bán.`,
         `Phát triển công nghiệp và nông nghiệp: Gần các khu công nghiệp lớn, thuận lợi cho việc phát triển các ngành công nghiệp chế biến cà phê và thực phẩm.`,
         `Sản xuất nông nghiệp: Đa số hộ dân tại phường sản xuất nông nghiệp, chủ yếu là các loại cây công nghiệp: cà phê, hồ tiêu và cây ăn trái.`,
      ],
      info_description: `Lưu giữ nhiều giá trị văn hóa bản địa, đặc biệt là văn hóa Ê Đê, tạo cơ hội phát triển du lịch cộng đồng bền vững.`,
      info: [
         `Các di sản văn hóa, địa danh tiêu biểu: Chợ Phan Đình Phùng, GO! Buôn Ma Thuột... `,
         `Các món ăn và đặc sản: Bánh tráng trộn, bún thịt nướng, cà đắng giã, canh cà đắng, các món ăn vặt…`,
      ],
   },
   {
      id: 86,
      province: 26,
      name: "Phường Ea Kao ",
      image: ["ea-kao-1.jpg"],
      introduce: `Phường Ea Kao được thành lập từ việc sáp nhập các phường Ea Tam và xã Ea Kao.`,
      square: `Diện tích: 60,70 km² `,
      population: `Dân số: Khoảng 57.000 người.`,
      ethnic: `Phường Ea Kao là nơi sinh sống của nhiều dân tộc khác nhau, chủ yếu là người Kinh, Ê Đê và một số dân tộc thiểu số khác: Tày, Nùng …`,
      location: [
         `Phía Bắc: Giáp phường Buôn Ma Thuột, phường Tân Lập`,
         `Phía Nam: Giáp xã Ea Na, xã Dray Bhăng.`,
         `Phía Đông: Giáp Ea Ktur, phường Tân Lập.`,
         `Ph phía Tây: Giáp xã Hòa Phú, phường Thành Nhất`,
      ],
      economy_description: `Hệ thống giao thông phát triển với các tuyến đường chính như Quốc lộ 14 và đường Y Wang tạo thuận lợi cho giao thương và phát triển kinh tế. Kinh tế chủ lực của phường là thương mại dịch vụ và nông nghiệp.`,
      economy: [
         `Thương mại và dịch vụ: Các hoạt động thương mại phát triển mạnh mẽ với các chợ truyền thống, cửa hàng tiện lợi và các dịch vụ du lịch homestay. Đặc biệt, Hồ Ea Kao là một danh lam thắng cảnh cấp tỉnh, với diện tích gần 289 ha, có cảnh quan thiên nhiên đẹp, thu hút du khách với các hoạt động như chèo thuyền độc mộc, câu cá và trải nghiệm văn hóa Ê Đê.`,
         `Sản xuất nông nghiệp: Phường Ea Kao nằm trong vùng đất bazan màu mỡ, phù hợp cho việc trồng các cây công nghiệp như cà phê, cây ăn trái.`,
      ],
      info_description: `Với cộng đồng dân cư bao gồm người Kinh và các dân tộc thiểu số như Ê Đê, Tày, Nùng, tạo nên một cộng đồng văn hóa phong phú. Các giá trị văn hóa truyền thống như lễ hội, âm nhạc dân gian và nghề thủ công được bảo tồn và phát huy, đặc biệt là văn hóa của người Ê Đê.`,
      info: [
         `Các di sản văn hóa, thắng cảnh tiêu biểu: Hồ Ea Kao, trường Đại học Tây Nguyên,... `,
         `Các món ăn và đặc sản: Các món chế biến từ cá nước ngọt tươi ngon của hồ Ea Kao như chả cá thác lác, lẩu cá lăng, …`,
      ],
   },
   {
      id: 87,
      province: 26,
      name: "Phường Buôn Hồ",
      image: ["buon-ho-1.jpg"],
      introduce: `Phường Tân An được thành lập từ việc sáp nhập các phường Đạt Hiếu, An Bình, An Lạc, Thiện An, Thống Nhất và Đoàn Kết.`,
      square: `Diện tích: 66,54 km² `,
      population: `Dân số: Khoảng 62.000 người.`,
      ethnic: `Cộng đồng đa dạng với người Kinh chiếm đa số, kèm theo các dân tộc thiểu số như Ê Đê, Tày, Nùng, M’nông…`,
      location: [
         `Phía đông giáp xã Pong Drăng, xã Ea Tul`,
         `phía tây giáp xã Ea Drông`,
         `phía nam giáp phường Cư Pao`,
         `phía bắc giáp xã Pong Drăng `,
      ],
      economy_description: `Hệ thống giao thông phát triển với các tuyến đường chính: Quốc lộ 14, quốc lộ 29 và đường liên xã, tạo điều kiện thuận lợi cho giao thương. Phường Buôn Hồ phát triển kinh tế mạnh mẽ nhờ vào sự kết hợp giữa nông nghiệp truyền thống, thương mại hiện đại và du lịch sinh thái.`,
      economy: [
         `Nghành công nghiệp: Cụm khu công nghiệp Tân An với diện tích 104,75 ha, với cơ sở hạ tầng được đầu tư nâng cấp, tạo điều kiện thuận lợi cho việc vận chuyển hàng hóa, thu hút nhiều dự án đầu tư, đặc biệt trong lĩnh vực công nghiệp chế biến nông sản, sản xuất công nghiệp, góp phần tăng trưởng kinh tế địa phương.`,
         `Sản xuất nông nghiệp: Phường Tân An với thổ nhưỡng đất đai màu mỡ, có thế mạnh phát triển các loại cây công nghiệp: Cà phê, cao su, hồ tiêu và cây ăn trái. `,
         `Phát triển đô thị, thương mại và dịch vụ: Phường Tân An được quy hoạch và phát triển với nhiều khu đô thị hiện đại: Khu đô thị mới EcoCity Premia, Khu đô thị mới Ân Phú, Khu đô thị mới Hiệp Phúc,… bên cạnh đó là hệ thống các tiện ích xã hội: siêu thị, chợ, khách sạn, bệnh viện, trường học,… tạo động lực cho phát triển kinh tế của phường. `,
         `Nông nghiệp công nghệ cao: Phường nổi tiếng với các vùng trồng cây công nghiệp như cà phê, hồ tiêu và cây ăn quả như bơ, sầu riêng. Các mô hình nông nghiệp công nghệ cao theo tiêu chuẩn VietGAP được áp dụng rộng rãi. `,
         `Thương mại dịch vụ: Với hệ thống các chợ truyền thống và các đầu mối thu mua các sản phẩm nông nghiệp tại địa phương, cùng với vị trí địa lý, giao thông  thuận lợi giao thương, giúp cho hoạt động thương mại của phường phát triển.`,
         `Du lịch sinh thái và văn hóa: Hồ Ea Blong Thượng và các buôn làng truyền thống của người Êđê với các hoạt động khám phá văn hóa bản địa, thưởng thức ẩm thực Tây Nguyên và trải nghiệm các tour du lịch sinh thái là những điểm nổi bật trong phát triển du lịch của phường.`,
      ],
      info_description: `Phường Buôn Hồ là nơi quy tụ nhiều cộng đồng dân tộc thiểu số, tiêu biểu như người Êđê và M’nông. Những giá trị văn hóa lâu đời như lễ hội cồng chiêng, nghề dệt thổ cẩm và các tập quán truyền thống tiếp tục được duy trì và phát triển. Bên cạnh việc bảo tồn, các hoạt động văn hóa còn được tổ chức định kỳ để tạo điểm nhấn du lịch và góp phần gắn kết cộng đồng. Đây không chỉ là biểu hiện của sự kế thừa mà còn thể hiện nỗ lực trong việc khẳng định bản sắc địa phương trong giai đoạn mới.`,
      info: [
         `Các di sản văn hóa, thắng cảnh tiêu biểu: Thác Dray Êga, Chùa Đạt Hiếu, hồ Ea Blong Thượng,... `,
         `Các món ăn và đặc sản: Bánh canh Hà Lan, Cơm lam, cá bống thác kho riềng, các món ăn từ rau rừng, bơ sáp, sầu riêng,...`,
      ],
   },
   {
      id: 88,
      province: 26,
      name: "Phường Cư Bao",
      image: ["cu-bao-1.jpg"],
      introduce: `Phường Cư Bao được thành lập từ việc sáp nhập phường Bình Tân, xã Bình Thuận và xã Cư Bao.`,
      square: `Diện tích: 104,94 km² `,
      population: `Dân số: Khoảng 36.000 người.`,
      ethnic: `Phường Cư Bao là nơi sinh sống của nhiều dân tộc khác nhau, chủ yếu là người Kinh, Ê Đê và một số dân tộc thiểu số khác: M’Nông, Ba Na, Tày…`,
      location: [
         `phía Đông giáp xã Ea Yông, xã Ea Phê`,
         `phía Tây giáp xã Cuôr Đăng`,
         `phía Nam giáp xã Krông Pắc`,
         `phía Bắc giáp phường Buôn Hồ, xã Ea Tul`,
      ],
      economy_description: ``,
      economy: [
         `Nông nghiệp – Công nghiệp chế biến: Canh tác cà phê, tiêu, cây ăn quả theo tiêu chuẩn VietGAP, phục vụ chế biến và xuất khẩu.`,
         `Du lịch sinh thái & văn hóa: Phát triển du lịch cộng đồng tại buôn làng, trải nghiệm văn hóa Tây Nguyên, tham quan rừng – nông trại – suối.`,
         `Thương mại – Dịch vụ & đô thị hóa: Là phường trung tâm của thị xã Buôn Hồ, có chợ, các cửa hàng, dịch vụ tiện ích cơ bản phục vụ cư dân. `,
      ],
      info_description: `Với cộng đồng dân cư đa dạng, bao gồm người Kinh và các dân tộc thiểu số, tạo nên sự giao thoa văn hóa phong phú và đặc sắc, lưu giữ nghề dệt thổ cẩm, sinh hoạt bản địa, góp phần bảo tồn văn hóa Tây Nguyên.`,
      info: [
         `Các di sản văn hóa, thắng cảnh tiêu biểu: Di tích lịch sử Địa điểm lưu niệm các chiến sĩ Trung đoàn 25, đèo Hà Lam,... `,
         `Các món ăn và đặc sản: Gà nướng, cá suối, rượu cần, rau rừng, …`,
      ],
   },
   {
      id: 89,
      province: 26,
      name: "Phường Phú Yên",
      image: ["phu-yen-1.jpg"],
      introduce: `Phường Phú Yên được thành lập từ việc sáp nhập Phường Phú Đông, Phường Phú Lâm, Phường Phú Thạnh, Xã Hòa Thành (thị xã Đông Hòa), một phần khu phố Uất Lâm (phường Hoà Hiệp Bắc, thị xã Đông Hòa) và Thôn Phú Nông (xã Hòa Bình 1, huyện Tây Hòa).`,
      square: `Diện tích: 44,04 km².`,
      population: `Dân số: Khoảng 61.000 người.`,
      ethnic: `Phường Phú Yên là nơi sinh sống của nhiều dân tộc khác nhau, chủ yếu là người Kinh, và một số dân tộc thiểu số khác: Chăm, Tày, Nùng…`,
      location: [
         `Phía Bắc: Giáp với phường Tuy Hòa`,
         `Phía Nam: Giáp với phường Đông Hòa`,
         `Phía Đông: Giáp Biển Đông.`,
         `Ph phía Tây: Giáp với xã Phú Hòa 1, xã Tây Hòa`,
      ],
      economy_description: `Với vị trí là đầu mối giao thông quan trọng (sân bay, đường bộ cao tốc, đường sắt), Phường Phú Yên có tiềm năng phát triển các ngành dịch vụ logistics, vận tải, du lịch.`,
      economy: [
         `Thương mại và Dịch vụ đô thị biển: Kinh tế phát triển nhờ địa thế ven đô – ven biển, kết hợp du lịch biển TP Tuy Hòa. Phát triển các khu đô thị mới, trung tâm thương mại, dịch vụ logistic, bến cảng nội bộ.`,
         `Thủy sản – Chế biến nông hải sản ven biển: Chuỗi dịch vụ hậu cần hải sản: thu mua, sơ chế – chế biến – logistics – phân phối. Liên kết với cảng biển Phú Yên đang được quy hoạch nâng cấp.`,
         `Du lịch – Dịch vụ: Nổi bật với phát triển homestay, resort ven đô, dịch vụ lưu trú – ẩm thực.`,
      ],
      info_description: ``,
      info: [
         `Là vùng trọng điểm văn hóa – lịch sử, nổi bật với: Các khu phố lâu đời, các khu đô thị mới. Di tích lịch sử – văn hóa cấp phường/xã như đình làng, nhà thờ họ, miếu tín ngưỡng cộng đồng.`,
         `Nhiều lễ hội truyền thống của người Kinh và dân tộc thiểu số tổ chức hàng năm năm.`,
         `Các di sản văn hóa, thắng cảnh tiêu biểu: Kè chắn sóng Xóm Rớ, cầu Hùng Vương,…`,
         `Các món ăn và đặc sản: Cơm gà Phú Yên, bún sứa Tuy Hòa, bánh canh hẹ, bún mực, bánh hỏi lòng heo, …`,
      ],
   },
   {
      id: 90,
      province: 26,
      name: "Phường Tuy Hoà",
      image: ["tuy-hoa-1.jpg"],
      introduce: `Phường Tuy Hoà được thành lập từ việc sáp nhập các phường 1, 2, 4, 5, 7 và một phần Phường 9 và phần còn lại của xã Hòa An (huyện Phú Hòa).`,
      square: `Diện tích: 73,71 km² `,
      population: `Dân số: Khoảng 44.000 người.`,
      ethnic: `Phường Tuy Hòa là nơi sinh sống của nhiều dân tộc khác nhau, chủ yếu là người Kinh và một số dân tộc thiểu số khác: Chăm, Tày, Nùng, Ba Na, …`,
      location: [
         `Phía đông: Giáp Biển Đông với bờ biển dài.`,
         `Phía tây: Giáp phườngPhú Hòa 2.`,
         `Phía nam: Giáp phường Phú Yên`,
         `Phía bắc: Giáp phường Bình Kiến.`,
      ],
      economy_description: `Phường Tuy Hòa có hệ thống cơ sở hạ tầng giao thông thuận lợi, hệ thống giáo dục, y tế và tiện ích công cộng được đầu tư hiện đại. Phường nằm gần Quốc lộ 1 và cao tốc Bắc Nam, tạo điều kiện thuận lợi cho giao thương và kết nối với các tỉnh lân cận.`,
      economy: [
         `Thương mại – Dịch vụ đô thị: Phường là đô thị phát triển, với các tiện ích thương mại và công cộng, tạo động lực cho sự phát triển dịch vụ – tài chính – y tế – giáo dục.`,
         `Thủy – hải sản & chế biến: Gắn liền với nền kinh tế ven biển: có cảng cá, sơ chế và phân phối hải sản.`,
         `Du lịch – Dịch vụ lưu trú: Phường Tuy Hòa là điểm đến du lịch: gần biển, có nhiều khách sạn, homestay, nhà hàng – là cơ hội phát triển mạnh nghành công nghiệp du lịch.`,
      ],
      info_description: `Khu vực trung tâm thành phố nên có nhiều di tích phường/xã như đình làng, chùa chiền, nhà thờ, kết hợp với các hoạt động lễ hội dân gian (cầu ngư, lễ hội truyền thống…). Cư dân vừa hiện đại vừa giữ hơi thở văn hóa truyền thống miền Trung.`,
      info: [
         `Các di sản văn hóa, thắng cảnh tiêu biểu: Tháp Nhạn, Hồ điều hòa Hồ Sơn, Bãi biển Tuy Hoà, Quảng trường 1-4,…`,
         `Các món ăn và đặc sản: Mắt cá ngừ đại dương, bún cá, bún sứa, bánh canh hẹ, bún mực, bánh bèo ngọt, bánh ướt Phú Yên, …`,
      ],
   },
   {
      id: 91,
      province: 26,
      name: "Phường Bình Kiến ",
      image: ["binh-kien-1.jpg"],
      introduce: `Phường Bình Kiến được thành lập từ việc sáp nhập các xã An Phú, Hòa Kiến, Bình Kiến và một phần Phường 9 (các khu phố Thanh Đức, Ninh Tịnh 3, Phước Hậu 2, Ninh Tịnh 6, Liên Trì 1 & 2, Phước Hậu 1) .`,
      square: `Diện tích: 73,71 km² `,
      population: `Dân số: Khoảng 44.000 người.`,
      ethnic: `Phường Tuy Hòa là nơi sinh sống của nhiều dân tộc khác nhau, chủ yếu là người Kinh và một số dân tộc thiểu số khác: Chăm, Ê Đê, Ba Na, Tày, Nùng, …`,
      location: [
         `Phía Bắc: Giáp xã Tuy An Nam`,
         `Phía Nam: Giáp phường Tuy Hòa, xã Phú Hòa 2`,
         `Phía Đông: Giáp biển đông`,
         `Phía Tây: Giáp xã Phú Hòa 2.`,
      ],
      economy_description: ``,
      economy: [
         `Với diện tich đất nông nghiệp rộng lớn, kinh tế của Bình Kiến phát triển nghề vườn, hình thành vùng chuyên canh rau xanh và trồng hoa cảnh nổi tiếng, cung ứng cho thị trường`,
         `Phường gắn kết giữa trung tâm đô thị và phần nông thôn tạo tiềm năng du lịch trải nghiệm: làng nghề, sinh thái, văn hóa bản địa`,
      ],
      info_description: `Bình Kiến có bề dày về lịch sử và văn hóa, là cái nôi cách mạng. Biểu tượng của Bình Kiến là núi Chóp Chài, đã đi vào ca dao, tục ngữ: Chóp Chài đội mũ, mây phủ Đá Bia… Văn hóa của Phường là sự hòa trộn giữa khu đô thị hiện đại và các vùng nông thôn truyền thống, phát huy lễ hội địa phương, nông thôn mới và văn hóa cộng đồng.`,
      info: [
         `Các di sản văn hóa, thắng cảnh tiêu biểu: Tháp Nghinh Phong, Bãi biển Long Thủy, Núi Chóp Chài, Chùa Bảo Lâm,... `,
         `Các món ăn và đặc sản: mắt cá ngừ đại dương, cơm gà Phú Yên, bánh hỏi lòng heo, bánh canh hẹ, bò một nắng, và các món hải sản tươi ngon, …`,
      ],
   },
   {
      id: 92,
      province: 26,
      name: "Phường Xuân Đài",
      image: ["xuan-dai-1.jpg"],
      introduce: `Phường Xuân Đài được thành lập từ việc sáp nhập phường Xuân Thành và phường Xuân Đài.`,
      square: `Diện tích: 13,40 km² `,
      population: `Dân số: Khoảng 21.000 người.`,
      ethnic: `Phường Xuân Đài là nơi sinh sống của nhiều dân tộc khác nhau, chủ yếu là người Kinh và một số dân tộc thiểu số khác: Ba Na, Ê Đê, …`,
      location: [
         `Phía đông: Giáp Vịnh Xuân Đài, một vịnh biển đẹp và nổi tiếng.`,
         `Phía tây: Giáp xã Xuân Thọ`,
         `Phía nam: Giáp xã Tuy An Đông`,
         `Phía bắc: Giáp phường Sông Cầu`,
      ],
      economy_description: `Với hệ thống giao thông hiện đại và các tuyến đường huyết mạch: Quốc lộ 14, Quốc lộ 26, đường tránh Đông, đường tránh Tây tạo thuận lợi cho hoạt động phát triển kinh tế và logistics của khu vực. Các ngành kinh tế chủ lực như công nghiệp, thương mại, dịch vụ, nông nghiệp đang được chú trọng để khai thác tối đa tiềm năng của phường.`,
      economy: [
         `Kinh tế biển: Xuân Đài nằm ở vịnh Xuân Đài, một lợi thế lớn để phát triển kinh tế biển. Hoạt động đánh bắt hải sản, nuôi trồng thủy sản và làm nước mắm là những ngành kinh tế chủ đạo.`,
         `Du lịch biển: Vịnh Xuân Đài với nhiều bãi biển đẹp, các đảo và các danh lam thắng cảnh đã thu hút nhiều dự án du lịch nghỉ dưỡng, góp phần đưa du lịch trở thành ngành kinh tế mũi nhọn của địa phương.`,
         `Làng nghề truyền thống: Các làng nghề làm nước mắm, đánh bắt hải sản và các hoạt động thủ công truyền thống khác tạo nên nét đặc trưng văn hóa và kinh tế của Xuân Đài`,
      ],
      info_description: `Văn hóa Xuân Đài là sự kết hợp hài hòa giữa truyền thống và hiện đại, với các giá trị văn hóa biển được bảo tồn và phát huy.Người dân Xuân Đài tự hào về quê hương, về những giá trị văn hóa truyền thống, tạo nên một cộng đồng đoàn kết và giàu bản sắc. `,
      info: [
         `Các di sản văn hóa, thắng cảnh tiêu biểu: Vịnh Xuân Đài, Gành Đèn, Gành Đỏ, bãi Từ Nham, bãi Ôm, và đảo Nhất Tự Sơn. `,
         `Các món ăn và đặc sản: bánh canh hẹ, bánh xèo, gỏi sứa, và các món hải sản tươi sống như sò huyết, ghẹ, ốc,...`,
      ],
   },
];

export default phuongxaDakLak;
