const dataDanToc = [
  { id: 1, name: `NGƯỜI BANA	` },
  { id: 2, name: `NGƯỜI BỐ Y	` },
  { id: 3, name: `NGƯỜI BRÂU	` },
  { id: 4, name: `NGƯỜI BRU-VÂN KIỀU` },
  { id: 5, name: `NGƯỜI CHĂM	` },
  { id: 6, name: `NGƯỜI CHƠ RO	` },
  { id: 7, name: `NGƯỜI CHU-RU	` },
  { id: 8, name: `NGƯỜI CHỨT` },
  { id: 9, name: `NGƯỜI CO	` },
  { id: 10, name: `NGƯỜI CƠ HO	` },
  { id: 11, name: `NGƯỜI CỜ LAO	` },
  { id: 12, name: `NGƯỜI CƠ TU` },
  { id: 13, name: `NGƯỜI CỐNG	` },
  { id: 14, name: `NGƯỜI DAO	` },
  { id: 15, name: `NGƯỜI Ê-ĐÊ	` },
  { id: 16, name: `NGƯỜI GIA RAI` },
  { id: 17, name: `NGƯỜI GIÁY	` },
  { id: 18, name: `NGƯỜI GIÉ-TRIÊNG	` },
  { id: 19, name: `NGƯỜI HÀ NHÌ	` },
  { id: 20, name: `NGƯỜI HOA` },
  { id: 21, name: `NGƯỜI HRÊ	` },
  { id: 22, name: `NGƯỜI KHÁNG	` },
  { id: 23, name: `NGƯỜI KHMER	` },
  { id: 24, name: `NGƯỜI KHƠ MÚ` },
  { id: 25, name: `NGƯỜI KINH	` },
  { id: 26, name: `NGƯỜI LA CHÍ	` },
  { id: 27, name: `NGƯỜI LA HA	` },
  { id: 28, name: `NGƯỜI LA HỦ` },
  { id: 29, name: `NGƯỜI LÀO	` },
  { id: 30, name: `NGƯỜI LÔ LÔ	` },
  { id: 31, name: `NGƯỜI LỰ	` },
  { id: 32, name: `NGƯỜI MẠ` },
  { id: 33, name: `NGƯỜI MẢNG	` },
  { id: 34, name: `NGƯỜI MNÔNG	` },
  { id: 35, name: `NGƯỜI MÔNG	` },
  { id: 36, name: `NGƯỜI MƯỜNG` },
  { id: 37, name: `NGƯỜI NGÁI	` },
  { id: 38, name: `NGƯỜI NÙNG	` },
  { id: 39, name: `NGƯỜI Ơ ĐU	` },
  { id: 40, name: `NGƯỜI PÀ THẺN` },
  { id: 41, name: `NGƯỜI PHÙ LÁ	` },
  { id: 42, name: `NGƯỜI PU PÉO	` },
  { id: 43, name: `NGƯỜI RA GLAY	` },
  { id: 44, name: `NGƯỜI RƠ MĂM` },
  { id: 45, name: `NGƯỜI SÁN CHAY	` },
  { id: 46, name: `NGƯỜI SÁN DÌU	` },
  { id: 47, name: `NGƯỜI SI LA	` },
  { id: 48, name: `NGƯỜI TÀ ÔI` },
  { id: 49, name: `NGƯỜI TÀY	` },
  { id: 50, name: `NGƯỜI THÁI	` },
  { id: 51, name: `NGƯỜI THỔ	` },
  { id: 52, name: `NGƯỜI XINH MUN` },
  { id: 53, name: `NGƯỜI XƠ ĐĂNG	` },
  { id: 54, name: `NGƯỜI XTIÊNG` },
]
export default dataDanToc;